### ISSUE TITLE
Install hangs failing to collect package metadata

### ISSUE THREAD

**Issue by vdet** [STOmics/Stereopy#123]
Hello,

While installing stereopy in an Apptainer container, conda hangs:
```
(st) Apptainer> conda install stereopy -c stereopy -c grst -c numba -c conda-forge -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): |  #spinning wheel, installer hangs until kill with ^C
```
Any idea about what went wrong?

In case this is relevant, the container was created with
```
singularity build stereopy.sif docker://ubuntu
```
I then entered in the container, installed miniconda, and  followed the procedure recommended in https://stereopy.readthedocs.io/en/latest/content/00_Installation.html

Let me know if more details are useful.

**Comment by vdet** [comment]
Could not solve the issue above, but ```pip install stereopy``` did work.

**Comment by limin321** [comment]
I have exactly the same issue while installing stereopy on Linux with conda. Then, I switch to pip install and it failed with error like this:
<img width="875" alt="Screen Shot 2023-05-18 at 10 58 11 AM" src="https://github.com/BGIResearch/stereopy/assets/42760669/2ef01574-1006-435e-a942-bf0508d78834">
Then, I tried pip `install stereopy --use-pep517`
it doesn't give me any error. Not sure what is supposed to be seen when installing successfully. While I try to import the package `import stereo as st ` , it gave me so many warning, not sure how these warning will affect later analysis.
<img width="1202" alt="Screen Shot 2023-05-18 at 11 01 26 AM" src="https://github.com/BGIResearch/stereopy/assets/42760669/f54abfce-aa13-4e78-8692-95fbf9da8cf3">

I would appreciate if someone can explain the warnings, and how successfully installing should look like.

**Comment by YAOJ-bioin** [comment]
I meet the same problem as above, Ii stopped ar using cashed `Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e5/24/6d7a55afa0f8aa420ddf8fa8ede8111398cc7887967dbcd0b55e56cdab48/stereopy-0.12.0.tar.gz (88.1 MB)
` when I use pip install -i https://pypi.tuna.tsinghua.edu.cn/simple stereopy.

**Comment by LyonLen** [comment]
> 

Hi? It is just hung by your manually typing ctrl+c?

**Comment by LyonLen** [comment]
> conda install stereopy -c stereopy -c grst -c numba -c conda-forge -c bioconda

Look like it is just hung by your manually typing ctrl+c.
I guess you are stuck at `Collecting package metadata (repodata.json)`?

**Comment by LyonLen** [comment]
> Hello,
> 
> While installing stereopy in an Apptainer container, conda hangs:
> 
> ```
> (st) Apptainer> conda install stereopy -c stereopy -c grst -c numba -c conda-forge -c bioconda
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): |  #spinning wheel, installer hangs until kill with ^C
> ```
> 
> Any idea about what went wrong?
> 
> In case this is relevant, the container was created with
> 
> ```
> singularity build stereopy.sif docker://ubuntu
> ```
> 
> I then entered in the container, installed miniconda, and followed the procedure recommended in https://stereopy.readthedocs.io/en/latest/content/00_Installation.html
> 
> Let me know if more details are useful.

Look like it is just hung by your manually typing ctrl+c.
Guess you are stuck at Collecting package metadata (repodata.json)?

**Comment by vdet** [comment]
> Look like it is just hung by your manually typing ctrl+c.

No. I typed ctrl+c to regain control of the terminal *after* ```conda install``` remained hanged for hours. So that's definitively not the issue.

> Guess you are stuck at Collecting package metadata (repodata.json)?

Rigth, no package is downloaded.

**Comment by LyonLen** [comment]
> > Look like it is just hung by your manually typing ctrl+c.
> 
> No. I typed ctrl+c to regain control of the terminal _after_ `conda install` remained hanged for hours. So that's definitively not the issue.
> 
> > Guess you are stuck at Collecting package metadata (repodata.json)?
> 
> Rigth, no package is downloaded.

You can try mamba-install instead of conda-install.
Mamba is much quicker than conda while collecting package metadata.
Re-create a clean conda environment.
`conda create -n try_mamba_install_st mamba -c conda-forge`
Install Stereopy (already include notebook and python3.8)
`mamba install stereopy -c stereopy -c grst -c numba -c conda-forge -c bioconda`

**Comment by LyonLen** [comment]
> I have exactly the same issue while installing stereopy on Linux with conda. Then, I switch to pip install and it failed with error like this: <img alt="Screen Shot 2023-05-18 at 10 58 11 AM" width="875" src="https://user-images.githubusercontent.com/42760669/239342536-2ef01574-1006-435e-a942-bf0508d78834.png"> Then, I tried pip `install stereopy --use-pep517` it doesn't give me any error. Not sure what is supposed to be seen when installing successfully. While I try to import the package `import stereo as st ` , it gave me so many warning, not sure how these warning will affect later analysis. <img alt="Screen Shot 2023-05-18 at 11 01 26 AM" width="1202" src="https://user-images.githubusercontent.com/42760669/239343203-f54abfce-aa13-4e78-8692-95fbf9da8cf3.png">
> 
> I would appreciate if someone can explain the warnings, and how successfully installing should look like.

Look like you had already installed `Stereopy` successfully.
`NumbaDeprecationWarning` was reported by site package `datashader`, which means that it is incompatible with `numba`.
We will fix that in the next version.
Thx for your report.

**Comment by limin321** [comment]
> pip install stereopy --use-pep517



> Hi,
> 
> I am encountered with the above problem as well. And I have tried all solutions mentioned above but failed.
> 
> When I run `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple stereopy` and `pip install stereopy --use-pep517`, the following error occurred. <img alt="截屏2023-06-22 22 14 29" width="1440" src="https://user-images.githubusercontent.com/105658106/247958588-d0ecbae9-3f45-4a87-a8b5-519d545542db.png"> <img alt="截屏2023-06-22 22 14 47" width="1440" src="https://user-images.githubusercontent.com/105658106/247958700-05a2deb0-ca23-4cb8-adcd-dfdf361d6e46.png"> <img alt="截屏2023-06-22 22 15 09" width="1440" src="https://user-images.githubusercontent.com/105658106/247958721-a4ae2548-b1b7-4ff2-a431-26bf6a43c530.png">
> 
> I want to know what should I do to successfully install stereopy. Thanks for your patience!

Not a Dev member, Could you please try `pip install stereopy --use-pep517`? I don't see you running it based on your screenshot. I helped someone else running this code and it works.

**Comment by sarahshuang** [comment]
> > pip install stereopy --use-pep517
> 
> > Hi,
> > I am encountered with the above problem as well. And I have tried all solutions mentioned above but failed.
> > When I run `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple stereopy` and `pip install stereopy --use-pep517`, the following error occurred. <img alt="截屏2023-06-22 22 14 29" width="1440" src="https://user-images.githubusercontent.com/105658106/247958588-d0ecbae9-3f45-4a87-a8b5-519d545542db.png"> <img alt="截屏2023-06-22 22 14 47" width="1440" src="https://user-images.githubusercontent.com/105658106/247958700-05a2deb0-ca23-4cb8-adcd-dfdf361d6e46.png"> <img alt="截屏2023-06-22 22 15 09" width="1440" src="https://user-images.githubusercontent.com/105658106/247958721-a4ae2548-b1b7-4ff2-a431-26bf6a43c530.png">
> > I want to know what should I do to successfully install stereopy. Thanks for your patience!
> 
> Not a Dev member, just try to help. Could you please try `pip install stereopy --use-pep517`? I don't see you running it based on your screenshot. I helped someone else running this code and it works.



Thx! Acturally I tried `pip install stereopy --use-pep517`, but the similar error occurred as well. 
<img width="1440" alt="截屏2023-06-23 09 27 37" src="https://github.com/STOmics/Stereopy/assets/105658106/22831262-5d36-474d-b63e-b5305249d70e">
<img width="1440" alt="截屏2023-06-23 09 27 44" src="https://github.com/STOmics/Stereopy/assets/105658106/a95168c9-0fbd-414a-b643-bed084c1ddb3">
<img width="1440" alt="截屏2023-06-23 09 27 55" src="https://github.com/STOmics/Stereopy/assets/105658106/4da7e65d-62af-4ec5-9081-c785f5952e96">
<img width="1440" alt="截屏2023-06-23 09 28 27" src="https://github.com/STOmics/Stereopy/assets/105658106/d1f7c41d-e9ed-48a7-a942-5de8ff55654b">
<img width="1440" alt="截屏2023-06-23 09 28 33" src="https://github.com/STOmics/Stereopy/assets/105658106/10919dca-0b9d-41aa-99ba-9fd8583a3fde">
<img width="1440" alt="截屏2023-06-23 09 29 09" src="https://github.com/STOmics/Stereopy/assets/105658106/53aa2155-748b-43e9-ba22-e4e259ebe47c">

**Comment by limin321** [comment]
> > > pip install stereopy --use-pep517
> > 
> > 
> > > Hi,
> > > I am encountered with the above problem as well. And I have tried all solutions mentioned above but failed.
> > > When I run `pip install -i https://pypi.tuna.tsinghua.edu.cn/simple stereopy` and `pip install stereopy --use-pep517`, the following error occurred. <img alt="截屏2023-06-22 22 14 29" width="1440" src="https://user-images.githubusercontent.com/105658106/247958588-d0ecbae9-3f45-4a87-a8b5-519d545542db.png"> <img alt="截屏2023-06-22 22 14 47" width="1440" src="https://user-images.githubusercontent.com/105658106/247958700-05a2deb0-ca23-4cb8-adcd-dfdf361d6e46.png"> <img alt="截屏2023-06-22 22 15 09" width="1440" src="https://user-images.githubusercontent.com/105658106/247958721-a4ae2548-b1b7-4ff2-a431-26bf6a43c530.png">
> > > I want to know what should I do to successfully install stereopy. Thanks for your patience!
> > 
> > 
> > Not a Dev member, just try to help. Could you please try `pip install stereopy --use-pep517`? I don't see you running it based on your screenshot. I helped someone else running this code and it works.
> 
> Thx! Acturally I tried `pip install stereopy --use-pep517`, but the similar error occurred as well. <img alt="截屏2023-06-23 09 27 37" width="1440" src="https://user-images.githubusercontent.com/105658106/248130993-22831262-5d36-474d-b63e-b5305249d70e.png"> <img alt="截屏2023-06-23 09 27 44" width="1440" src="https://user-images.githubusercontent.com/105658106/248131055-a95168c9-0fbd-414a-b643-bed084c1ddb3.png"> <img alt="截屏2023-06-23 09 27 55" width="1440" src="https://user-images.githubusercontent.com/105658106/248131160-4da7e65d-62af-4ec5-9081-c785f5952e96.png"> <img alt="截屏2023-06-23 09 28 27" width="1440" src="https://user-images.githubusercontent.com/105658106/248131240-d1f7c41d-e9ed-48a7-a942-5de8ff55654b.png"> <img alt="截屏2023-06-23 09 28 33" width="1440" src="https://user-images.githubusercontent.com/105658106/248131296-10919dca-0b9d-41aa-99ba-9fd8583a3fde.png"> <img alt="截屏2023-06-23 09 29 09" width="1440" src="https://user-images.githubusercontent.com/105658106/248131348-53aa2155-748b-43e9-ba22-e4e259ebe47c.png">

I saw you are using Mac. That is the issue. I never figure out how to install it on Mac, then I gave up. The tool is not compatible with Mac yet. Try using a Linux system.

**Comment by sarahshuang** [comment]
> 

Many thanks for your reply! Okay, I will try using a Linux system and hope it could work well.

**Comment by sarahshuang** [comment]
> I saw you are using Mac. That is the issue. I never figure out how to install it on Mac, then I gave up. The tool is not compatible with Mac yet. Try using a Linux system.

Many thanks for your reply and suggestion! Okay, I will try using a Linux system and hope it will work finally.

**Comment by playgamemy** [comment]
Just reporting the same issue happended with both my Windows machine. Cannot install Stereopy using Conda following the instruction, keep spinning in solving environment after retry with next repodata source.
Tried both specifying stereopy channel or just using the default channel and still the same.
![image](https://github.com/STOmics/Stereopy/assets/24202933/c77338a5-f82d-41f9-9b7d-34260a368690)

**Comment by sarahshuang** [comment]
> 

 Maybe you could try `pip install stereopy --use-pep517`! By running the code, I successfully install stereopy in Linux system.

**Comment by sarahshuang** [comment]
> Just reporting the same issue happended with both my Windows machine. Cannot install Stereopy using Conda following the instruction, keep spinning in solving environment after retry with next repodata source. Tried both specifying stereopy channel or just using the default channel and still the same. ![image](https://user-images.githubusercontent.com/24202933/251063198-c77338a5-f82d-41f9-9b7d-34260a368690.png)

Maybe you could try pip install stereopy --use-pep517! By running the code, I successfully installed stereopy in Linux system.

**Comment by playgamemy** [comment]
> > Just reporting the same issue happended with both my Windows machine. Cannot install Stereopy using Conda following the instruction, keep spinning in solving environment after retry with next repodata source. Tried both specifying stereopy channel or just using the default channel and still the same. ![image](https://user-images.githubusercontent.com/24202933/251063198-c77338a5-f82d-41f9-9b7d-34260a368690.png)
> 
> Maybe you could try pip install stereopy --use-pep517! By running the code, I successfully installed stereopy in Linux system.

I can indeed confirm installation of stereopy package in the new conda environment using pip instead, in both of my windows 11 machines with no error.

FYI my conda is 23.3.1, and pip within the python3.8 conda environment is 23.1.2.
I have tried to create a new conda environement with stereopy package satisfied, and finally get the conflict error spit out which packages are in conflict. Attached below for R&D team reference to be resolved before rebuilding for the conda package.
![image](https://github.com/STOmics/Stereopy/assets/24202933/4cd02ba3-0edd-48bd-bd63-1a8b3f0118f8)

If conda package build for Windows x64 remaining an issue, and pip is the recommended way to go, maybe edit the installation tutorial and have pip as the first recommended method.

**Comment by waniwal** [comment]
I met the same problem. I eventually solved using run  pip install  stereopy  in cmd as the terminal administrator's.
