### ISSUE TITLE
Spatially constrained clustering (SCC) 

### ISSUE THREAD

**Issue by tvegawaichman** [STOmics/Stereopy#131]
Hello!
I'm looking for the spatially constrained clustering (SCC) algorithm for spatial clustering that is mentioned here (https://doi.org/10.1016/j.cell.2022.04.003)
I want to know if it is implemented in the package

**Comment by UglyRay7** [comment]
Sorry for the late reply to your question.

Spatially constrained clustering (SCC) algorithm has not been imported into our package yet. But it can be implemented in Spateo now.

Hope my answer will be helpful!
Ray

**Comment by tvegawaichman** [comment]
Perfect, thank you very much!
