### ISSUE TITLE
How to subset stereopy object?

### ISSUE THREAD

**Issue by GokceOGUZ** [STOmics/Stereopy#134]
I have run the Square bin tutorial on my data and got my clusters. Now, I would like to subset the object according to my cluster of interests and do fine clustering with the new object.

I cannot use the `add_select_area()` code as the clusters are spread around. So I was wondering if there a specific function for subsetting based on cluster information.

To give an example, let's say I want to do fine clustering on cluster 4 & 7. How to generate a new subsetted object ?
![image](https://github.com/STOmics/Stereopy/assets/22001565/dc75cc9f-a2ad-429e-93cf-ee7203aeadb9)

Thanks!

**Comment by tanliwei-coder** [comment]
Hi!!

If the version of the stereopy you installed is greater than 0.12.0, you can run datasubset = data.tl.filter_by_clusters(cluster_res_key='leiden', groups=['4', '7'], excluded=False, inplace=False) to get a new data object, the `cluster_res_key` is the same as the parameter `res_key` of the clustering function you ran.

**Comment by GokceOGUZ** [comment]
Dear [tanliwei-coder](https://github.com/tanliwei-coder),

Thanks for your response and quick implementation to the workflow. I have 2 follow-up questions:

1- I am running the code as you suggested but receiving the `AttributeError: 'StereoExpData' object has no attribute '_position_z'` error. Is this possible because the object I am using was generated with an earlier stereopy version ? Is there a solution for this ?
![image](https://github.com/STOmics/Stereopy/assets/22001565/c9216a1b-34ce-4073-8b84-c963dbf3ea5b)

2- I also ran the workflow with the stereopy 0.12.1, but getting the following  **_Indexing Error_** message. How may I fix it?
![image](https://github.com/STOmics/Stereopy/assets/22001565/cb2aa1ec-f694-4141-862f-dc64c85ed94f)

Thank you so much for your attention and help!

**Comment by tanliwei-coder** [comment]
Sorry, we will fix this bug as soon as possible.

**Comment by UglyRay7** [comment]
We have fixed this function, please update the package to 0.13.0b1. 

Thanks for your feedback and suggestion!
Ray
