### ISSUE TITLE
cell segmentation tutorial fail to generate the results.

### ISSUE THREAD

**Issue by limin321** [STOmics/Stereopy#137]
Hi,
I followed cell segmentation tutorial to set up running V3, V1, and DeepCell model. Based on the scripts, the 3 models all ran with no issue. However, the image results are different from the tutorial.

Here is the output of V1 model:
<img width="692" alt="Screen Shot 2023-06-27 at 3 21 45 PM" src="https://github.com/STOmics/Stereopy/assets/42760669/431b2d55-6021-46c8-8cfc-f615ae7c5ff1">

Here is the output of 
<img width="755" alt="Screen Shot 2023-06-27 at 3 22 12 PM" src="https://github.com/STOmics/Stereopy/assets/42760669/22f2df8d-f1b1-4045-9cb2-c97da880618a">

However, V3 model only has one file called SS200000135TL_D1_regist.cell_cut.tif.
First question, how many files do I expect to see from V3 model?

Second question, when I open the XX_regist_mask.tif, here is what I see.
V1 model mask.tif
<img width="584" alt="Screen Shot 2023-06-27 at 3 28 32 PM" src="https://github.com/STOmics/Stereopy/assets/42760669/53fe73ea-a092-4870-aa2d-b9f00cc19e3c">

DeepCell model mask.tif
<img width="712" alt="Screen Shot 2023-06-27 at 3 29 19 PM" src="https://github.com/STOmics/Stereopy/assets/42760669/c15befda-0d3d-47c0-8280-10620ba4b1f5">

V3 model doesn't have this mask.tif file.

Really appreciate your help,

Best,

LC

**Comment by TheSallyGardens** [comment]
@limin321 Hi！
Question 1 : V3 model has only one output, namely SS200000135TL_D1_regist.cell_cut.tif.
Question 2 ： The tif generated by the DeepCell model can be viewed by adjusting the contrast using imageJ.

Best,

TheSallyGardens

**Comment by limin321** [comment]
> @limin321 Hi！ Question 1 : V3 model has only one output, namely SS200000135TL_D1_regist.cell_cut.tif. Question 2 ： The tif generated by the DeepCell model can be viewed by adjusting the contrast using imageJ.
> 
> Best,
> 
> TheSallyGardens

@TheSallyGardens ,

Thank you so much for the help. It works in imageJ, though my images of the 3 models are not colorful. I am also able to generate the cell-bin files for them. 
I am going to close my this topic.

Best,
LC
