### ISSUE TITLE
region flag for read_gem

### ISSUE THREAD

**Issue by ViHammer** [STOmics/Stereopy#138]
`read_gef()` already supports passing a region to reduce the size of the data set. This is not supported by `read_gem()`, but would be greatly appreciated.

Is there a subset function that can be applied to StereoExpData objects?

**Comment by tanliwei-coder** [comment]
Hi!

You can use the function `data.tl.filter_coordinates` to filter data by setting `min_x`, `min_y`, `max_x` and `max_y`.

For example:
`data.tl.filter_coordinates(min_x=100, max_x=500, min_y=100, max_y=100)`
