### ISSUE TITLE
ModuleNotFoundError: No module named 'stereo.algorithm.highly_varialble_genes'

### ISSUE THREAD

**Issue by sarahshuang** [STOmics/Stereopy#139]
Hi, 

When following the guide of Quick Start(Cell Bin), I am encountered with the following error. Could anyone pls give me some selectable solutions? Thanks a lot! 
<img width="996" alt="截屏2023-06-29 14 07 47" src="https://github.com/STOmics/Stereopy/assets/105658106/60c8f43a-f137-436f-bbf6-6194b92aed3c">

**Comment by tanliwei-coder** [comment]
Hi!

The name of function you ran is wrong, it should be `highly_variable_genes`, there is an extra 'l' in variable.

**Comment by sarahshuang** [comment]
> Hi!
> 
> The name of function you ran is wrong, it should be `highly_variable_genes`, there is an extra 'l' in `variable`.

Aha, I see. What a stupid mistake it is! Thank you!! I will be more careful.
