### ISSUE TITLE
Error: Missing required datasets 'levels' and 'values'

### ISSUE THREAD

**Issue by mcraftt** [STOmics/Stereopy#146]
I ran the code for format conversion:
Rscript annh5ad2rds.R --infile aa.h5ad --outfile aa.rds

here's what i got:

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching SeuratObject
Registered S3 method overwritten by 'SeuratDisk':
  method            from  
  as.sparse.H5Group Seurat
Warning: Unknown file type: h5ad
Creating h5Seurat file for version 3.1.5.9900
Adding X as data
Adding raw/X as counts
Adding meta.features from raw/var
Adding spatial as cell embeddings for spatial
Adding raw_cellname to miscellaneous data
Adding raw_counts to miscellaneous data
Adding raw_genename to miscellaneous data
Adding sn to miscellaneous data
[1] "Finished! Converting h5ad to h5seurat file at:"
[2] "aa.h5seurat"                          
Validating h5Seurat file
Initializing Spatial with data
Adding counts for Spatial
Adding feature-level metadata for Spatial
Adding reduction spatial
Adding cell embeddings for spatial
Adding miscellaneous information for spatial
Adding command information
Adding cell-level metadata
Error: Missing required datasets 'levels' and 'values'
In addition: Warning message:
Cannot add objects with duplicate keys (offending key: spatial_), setting key to 'spatialos_' 
Execution halted

**Comment by tanliwei-coder** [comment]
Sorry for replying so late, the version `0.13.0b1` there is an error on this functionality, you can downgrade to `0.12.1` and try again, and notice that you should run `data.tl.cal_qc`  before `data.tl.raw_checkpoint`.
