### ISSUE TITLE
Extract cellbin assignments of individual DNBs

### ISSUE THREAD

**Issue by bmill3r** [STOmics/Stereopy#157]
Hello,

Is there a way to get the labels of the cellbins and the IDs or coordinates of the DNBs that were assigned to each cellbin in a cellbin GEF file? For example, in previous example data I have looked at (in this case, a GEM_CellBin.tsv.gz file), the matrix was something like:

```
A data.frame: 6 × 5
geneID	x	y	UMICount	label
<chr>	<int>	<int>	<int>	<dbl>
1	Gm26825	13476	11944	1	27298
2	Gm42418	13476	11944	1	27298
3	Pja1	8758	13656	1	37442
4	Cx3cl1	8758	13656	1	37442
5	Mgat3	11661	11611	1	25246
6	Gng3	5630	14950	1	44380

```

Where `x` and `y` are coordinates of the individual DNBs, and `label` is the cellbin each DNB was assigned to. Is it possible to extract something like this from the cellbin.gef file?
 
My goal is essentially to visualize the DNBs with respect to the different cellbins (ie, "cells") they were assigned to. Perhaps getting something like this:

![image](https://github.com/STOmics/Stereopy/assets/8630519/30016467-77e1-4dca-961b-58ce7b88a314)

 
Thanks,
Brendan

**Comment by tanliwei-coder** [comment]
There are no DNBs infomation in cellbin GEF because it has already aggregated all DNBs to corresponding cellbins.

**Comment by bmill3r** [comment]
Hi @tanliwei-coder,

Ok thanks for letting me know!

Brendan

**Comment by bmill3r** [comment]
Hi @bhavaygg it's been a while since I worked on this but to my memory I don't believe I was able to from the gef file. But I think you might do it by getting the DNB spatial coordinates and indices from the raw data and then overlay the cell masks to assign them to cells. Sorry I can't be more helpful.
