### ISSUE TITLE
TypeError: base_scatter() got an unexpected keyword argument 'groups'

### ISSUE THREAD

**Issue by danammak** [STOmics/Stereopy#161]
TypeError: base_scatter() got an unexpected keyword argument 'groups'

How can I plot cluster_scatter using Leiden algorithm with 'Groups' function?
I encounter the above error but I see that the function can be used with Groups. Can you please suggest on this?

**Comment by tanliwei-coder** [comment]
This function is added from v0.12.0, please to check the version which you are using.
