### ISSUE TITLE
Looking forward to the early implementation of batch correction algorithm between different slices.

### ISSUE THREAD

**Issue by ying1e** [STOmics/Stereopy#167]

**Comment by tanliwei-coder** [comment]
Hi!!  Could you provide more description about your question.

**Comment by ying1e** [comment]
How to eliminate non-biological batch differences between different sequencing chips due to technical problems?

**Comment by tanliwei-coder** [comment]
Currently, stereopy only have one algorithm to remove batches effect which is based on harmony algorithm, you can get further information about using it from [here](https://stereopy.readthedocs.io/en/latest/Tutorials/Batch_Effect.html).

**Comment by ying1e** [comment]
Thank you!
