### ISSUE TITLE
GEF to cGEF file process died

### ISSUE THREAD

**Issue by predictowner** [STOmics/Stereopy#169]
Hi,

I'm trying to convert GEF to cGEF file using tools:

**from stereo.tools.cell_cut import CellCut

cgef_out_dir = "./cell_cut_out"
bgef_path = "../.raw.gef"
mask_path = "../mask.tif"

cc = CellCut(cgef_out_dir=cgef_out_dir)
out_path = cc.cell_cut(bgef_path=bgef_path, mask_path=mask_path)**

But it seems that notebook died always. GEF file is around 3.4GB. Is it due to the short of RAM or is there other solution that I can make the transfer.

Many thanks!

**Comment by UglyRay7** [comment]
What is the equipment configuration of your computer or cluster server?

Ray

**Comment by predictowner** [comment]
Hi Ray,

I'm using cluster server with 40 core with 8G for each. Is that enough?

Thx

**Comment by tanliwei-coder** [comment]
because of a part of memory is occupied by system, the remaining memory can be used must be less than 8G, i note that the size of your data has reached almost half of the memory, I think it is not enough, you can try to increase the memory to 16G to try again.

**Comment by tanliwei-coder** [comment]
Could you go into shell to run it? it may able to get more infomation about this problem.
