### ISSUE TITLE
AttributeError: 'MSData' object has no attribute 'integrate'

### ISSUE THREAD

**Issue by Biomamba** [STOmics/Stereopy#174]
Dear author:
  Thank you for your contribution.
  Function ms_data.integrate() is seemed to disappear. Cloud you tell me how to solve it? My stereopy version is 0.12.1.

![image](https://github.com/STOmics/Stereopy/assets/104115877/b4619bdf-566d-4729-8ffd-888d98ae5ca4)

**Comment by UglyRay7** [comment]
Please install Stereopy of the latest version, or version >= 0.13.0b1.

Ray
