### ISSUE TITLE
Is there a way to calculate variance for PCA analysis and elbow plot in Stereopy?

### ISSUE THREAD

**Issue by danammak** [STOmics/Stereopy#175]
Hi Team,

I see that there is a following function:
 "StPipeline.pca(use_highly_genes=False, n_pcs=None, svd_solver='auto', hvg_res_key='highly_variable_genes', res_key='pca')"  
to calculate Principal Components but how do I decide how many PCs I can consider further for downstream analysis. I could not find any function to calculate variance and plot elbow/scree plot. Please suggest me on this.

**Comment by UglyRay7** [comment]
Currently, our tool does not support a ready-to-use plotting function for PCA elbow/scree plot which displays the contribution of PCs. Thanks for your feedback, and this function will be developed in a later version.

Ray
