### ISSUE TITLE
More samples within the same slice

### ISSUE THREAD

**Issue by MariaRosariaNucera** [STOmics/Stereopy#176]
Hi, thank you for the beautiful tool!
I have one question, from the tutorial I can see the option on how to analyse one single sample and slice, or multiple slices.
I am not sure how to deal with the case of multiple samples on the same slice.
What should I do in this case, is there a way to separate them?

Thank you
Maria

**Comment by UglyRay7** [comment]
I don't know if I got you correctly. It's like several slices have been integrated into one slice? So you just have one data file now?
If your data is in AnnData h5ad format, you could use the AnnData library to separate them.

Ray

**Comment by MariaRosariaNucera** [comment]
> I don't know if I got you correctly. It's like several slices have been integrated into one slice? So you just have one data file now? If your data is in AnnData h5ad format, you could use the AnnData library to separate them.
> 
> Ray

 It's not like several slices have been integrated into one slice, there was no integration, the tissues are physically located in the same slide.

I have the coordinates and the anndata, but I don't understand why I am not able to capture them using the function data.plt.interact_spatial_scatter(),  I can select the area but I am not able to store it in any way.

**Comment by Zhenbin24** [comment]
I'm very sorry for taking so long to reply. You can refer to this information to deal with it.

[url](https://stereopy.readthedocs.io/en/latest/Tutorials/Interactive_Visualization.html)
