### ISSUE TITLE
about data.tl.spatial_hotspot

### ISSUE THREAD

**Issue by Biomamba** [STOmics/Stereopy#179]
Dear authors:
  Thank your for your contribution to stereopy. There is a question really confuse me. Why parameters both use_highly_genes and use_raw can be True in function data.tl.spatial_hotspot()?

![image](https://github.com/STOmics/Stereopy/assets/104115877/37364374-143d-478b-92ca-b00079ea8f66)

**Comment by tanliwei-coder** [comment]
Sometimes, before `spatial_hotspot`, we would do some preprocessing which will change the value of expression matrix like normalize_total or log1p, setting `use_raw` to true represents use the expression matrix in which the values is raw value and setting `use_highly_genes` to true represents use the subset which only contains the highly variable genes, if both are set to true, the values of expression matrix in the subset are raw value.

**Comment by Biomamba** [comment]
> Sometimes, before `spatial_hotspot`, we may do some preprocessing which will change the values of expression matrix like `normalize_total` or `log1p`, setting `use_raw` to true represents using the expression matrix in which the values are raw values and setting `use_highly_genes` to true represents using the subset which only contains the highly variable genes, if both are set to true, the values of expression matrix in the subset are raw values.

Got it， thank you for your reply.
