### ISSUE TITLE
annh5ad2rds.R Error

### ISSUE THREAD

**Issue by suye0620** [STOmics/Stereopy#180]
![image](https://github.com/STOmics/Stereopy/assets/71215104/93d05012-436a-4c7b-a157-da1ecc2bd15a)
当我尝试annh5ad2rds.R对一个h5ad数据：https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/E9.5_E1S1.MOSTA.h5ad，进行转换时，报错了。
我不知道这部分代码中对于坐标数值的一系列操作是什么含义，希望得到帮助和fix，谢谢

**Comment by tanliwei-coder** [comment]
Sorry for replying too late!!! In a older Stereopy, we save some values into h5ad, it caused this error, you can upgrade Stereopy to latest version 1.0.0 to avoid this error.
