### ISSUE TITLE
data.plt.grn_dotplot() TypeError: unhashable type: 'DataFrame'

### ISSUE THREAD

**Issue by Biomamba** [STOmics/Stereopy#181]
Dear author:
   I have successed performed the GRN prediction and the heatmap visualization worked. However, the function data.plt.grn_dotplot of latest version has changed. The first parameter should be a str rather than DataFrame. 
`data.plt.grn_dotplot(data.tl.result['leiden'],network_res_key='regulatory_network_inference')`
![image](https://github.com/STOmics/Stereopy/assets/104115877/c551b94d-1dd8-4251-b233-a2596719c642)

  
`data.plt.grn_dotplot(data.tl.result['leiden'],network_res_key='regulatory_network_inference')`

 However, when I change it to str. I still met the following TypeError: 
`data.plt.grn_dotplot(cluster_res_key='leiden',
                     network_res_key='regulatory_network_inference')`  
![image](https://github.com/STOmics/Stereopy/assets/104115877/198cd638-1a2c-4843-9041-f834d9f4d26b)  

Cloud you please tell me how to solved it?

**Comment by tanliwei-coder** [comment]
Sorry, the tutorial makes a little mistask, the first parameter of `grn_dotplot` is only need to set to 'leiden' which specifies the clustering result.

**Comment by Biomamba** [comment]
> Sorry, the tutorial makes a little mistask, the first parameter of `grn_dotplot` is only need to set to 'leiden' which specifies the clustering result.

Thank you for your reply, but it still doesn't work when I change `data.tl.result['leiden']` into `'leiden'`.

**Comment by Biomamba** [comment]
> > Sorry, the tutorial makes a little mistask, the first parameter of `grn_dotplot` is only need to set to 'leiden' which specifies the clustering result.
> 
> Thank you for your reply, but it still doesn't work when I change `data.tl.result['leiden']` into `'leiden'`.
Following is the error:
![image](https://github.com/STOmics/Stereopy/assets/104115877/8168df5b-6073-4504-923f-fe5beaf3d974)

**Comment by tanliwei-coder** [comment]
Sorry, a bug is catched by you, there is a temporary solution, you can enter into the installed directory of stereopy and find out the file where grn_dotplot is located to eliminate this bug, you can do it like below:

```
import os
import stereo as st
root_dir = os.path.dirname(st.__file__)
print(os.path.join(root_dir, 'algorithm/regulatory_network_inference/plot_grn.py'))
```
Now, you can get the path of file containing `grn_dotplot`, and then, open this file and locate to line 321, change the 'bin' to 'bins', i think it can work.
