### ISSUE TITLE
anndata_to_stereo AnnData format conversion

### ISSUE THREAD

**Issue by wdb-web** [STOmics/Stereopy#182]
**anndata_to_stereo** does not transform obs, var, uns, obsm, varm data inside **AnnData**

**Comment by tanliwei-coder** [comment]
Hi!! you can use read_h5ad to load a h5ad file or a AnnData object, further infomation in [api](https://stereopy.readthedocs.io/en/latest/content/stereo.io.read_h5ad.html).
