### ISSUE TITLE
Where can we find information about the structure of the StereoExpData object?

### ISSUE THREAD

**Issue by Li-ZhiD** [STOmics/Stereopy#183]
Hi,

I want to learn about data management in StereoExpData object. Specifically, I am interested in extracting the expression matrix, embedding, DEGs etc. Where can I find this information?

Thanks!

**Comment by UglyRay7** [comment]
Sorry for not getting back to you sooner.

The format of StereoExpData is similar to AnnData. After finishing several analyses, type the data variable to show the basic information and results of StereoExpData.
![1697188971920](https://github.com/STOmics/Stereopy/assets/108983195/06bc235c-438d-45b7-a619-0318f094946d)
![1697189078025](https://github.com/STOmics/Stereopy/assets/108983195/7db1592d-47fc-4d8a-a89e-7ae01336e3ec)

Ray
