### ISSUE TITLE
AttributeError: No attribute named 'StPipeline.co_occurrence'

### ISSUE THREAD

**Issue by Biomamba** [STOmics/Stereopy#184]
When I run data.tl.co_occurrence() function in version 0.13.0b1, I met the following problem:
`data.tl.co_occurrence(
        method='stereopy',
        cluster_res_key='leiden',
        res_key='co_occurrence',
        dist_thres=300, # max threshold to measure co-occurence
        steps=10,  # step numbers to divide threshold interval evenly
        genelist=None,
        gene_thresh=0, # min threshold for gene expression in a cell
        n_jobs=-1
        )
File ~/miniconda3/envs/stereopy/lib/python3.8/site-packages/stereopy-0.13.0b1-py3.8.egg/stereo/algorithm/algorithm_base.py:91, in AlgorithmBase.get_attribute_helper(item, stereo_exp_data, res)
     89     __import__(f"stereo.algorithm.{item}")
     90 except:
---> 91     raise AttributeError(f"No attribute named 'StPipeline.{item}'")
     93 # TODO: this may be not the best way to get sub-class
     94 # num of subclasses may be like 100-200 at most
     95 for sub_cls in AlgorithmBase.__subclasses__():

AttributeError: No attribute named 'StPipeline.co_occurrence'
`
It seems version update brings too much function errors and object inheriting problems. I have submitted some of them in github issures. Cloud you please give us some methods to solve them?

**Comment by UglyRay7** [comment]
Co-occurrence analysis can be found in version 0.14.0b1, please install stereopy==0.14.0.b1.

Ray

**Comment by Biomamba** [comment]
> Co-occurrence analysis can be found in version 0.14.0b1, please install stereopy==0.14.0.b1.
> 
> Ray

Thank you for your reply. This problem has been solved by update stereopy into version 0.14.0b1.
