### ISSUE TITLE
About time consume.

### ISSUE THREAD

**Issue by Biomamba** [STOmics/Stereopy#186]
Dear author：
  Thank you for your contribution in developing such a wonderful tool for spatial transcription analysis like stereopy. However, some chapters in official tutorial, such as singler, grn, ccd, cell communication and so on, cost a lot of time. Besides, test files of different chapter are usally different.  Moreover, Cloud you please provide a demo data in order to improve the study effeciency?

**Comment by UglyRay7** [comment]
Thanks for your feedback.

For different analyses, we interpret the functions based on more appropriate data individually.  Later, we will try to provide a general or big demo case that incorporates as many analysis functions as possible.

Ray
