### ISSUE TITLE
MIDCount means?

### ISSUE THREAD

**Issue by predictowner** [STOmics/Stereopy#187]
Hi,

I want to ask a basic question about how the MIDCount was calculated from both GEM and GEF file.

Q1: Based on what I understand, in the GEM file, MIDCount is the fragment counts that dropped on each gene exon region, is that true? Whether alternative splicing forms for same gene are also taken into account? Could I add ExonCount together to get the MIDCount value?

Q2: During switch from GEM to GEF file, is this MIDCount still un-Normalized, which should be the same value in GEM file under same bin condition?

Thanks very much!

**Comment by UglyRay7** [comment]
Hi
A1: MIDcount is the fragment count dropped on each gene region (exon and intron), which includes  ExonCount. In GEM and GEF files you can find ExonCount items directly.
A2: It is just a transformation between file formats, not involving changes in values.

Ray
