### ISSUE TITLE
SingleR HPCA reference dataset - rda2h5ad.R throwing error

### ISSUE THREAD

**Issue by GokceOGUZ** [STOmics/Stereopy#190]
Hi, 

I am using the v14.0b1 to run the SingleR.

I would like to use the HPCA as the reference dataset. I downloaded the RDA format from the singleR website and tried to convert using the  `docs/source/_static/rda2h5ad.R` as suggested on the [tutorial page](https://stereopy.readthedocs.io/en/latest/Tutorials/SingleR.html). But it failed because the R code assumes the object is Summerized Experiment where singleR provides list. So:

1.  Is there an alternate code to convert SingleR references to h5ad?
2. Is there another database where I can download the SingleR references as Rdata or h5ad format ?

Regards,
Gokce

![image](https://github.com/STOmics/Stereopy/assets/22001565/79ae1563-9798-41cc-bbbd-afa9a0aef2df)
![image](https://github.com/STOmics/Stereopy/assets/22001565/c8e1e8d0-8cda-4fe7-b2a1-fafb48cb349f)

**Comment by GokceOGUZ** [comment]
Also I downloaded the _l5_all.h5ad_ reference data, tried to read in but getting the error below:
![image](https://github.com/STOmics/Stereopy/assets/22001565/e2837086-ea0f-40f3-9a96-74c5b1813310)

I have updated my anndata to 0.8 version but still the error persists. I will be really glad if you can enlighten me what am I missing.

Regards,
Gokce

**Comment by GokceOGUZ** [comment]
Ok, I found the answer to my original post. In R, we can  use the SingleR package & get the SummerizedExperiment version of the reference dataset by using the reference-based functions (`HumanPrimaryCellAtlasData(), BlueprintEncodeData(), DatabaseImmuneCellExpressionData(), NovershternHematopoieticData(), MonacoImmuneData()` )

**Comment by Zhenbin24** [comment]
Hello, you can refer to this method (https://stereopy.readthedocs.io/en/latest/Tutorials/Format_Conversion.html) to convert the file into h5ad format
