### ISSUE TITLE
how many _relationship options in MSData?

### ISSUE THREAD

**Issue by Sophia409** [STOmics/Stereopy#191]
Hi,

I am using the v14.0b1 to do MSData construction.

I'm wondering how to  choose _relationship parameter? The default value is 'other', but you say it could be changed simply (such as ms_data.relationship='continuous'). Are there any other options besides 'other' and 'continuous' ? 

I couldn't find detailed explaination about this in documentation of the functions. .
Regards,
Sophia

**Comment by UglyRay7** [comment]
There are three relationships among multiple data.
'continuous' : the ones in ms_data are from successive slices of a tissue specimen.
'time_series' : the ones in ms_data are from different-period tissue specimens of a specific species.
'other' : other possible relationships.
The first two are the most commonly used.

Ray
