### ISSUE TITLE
No attribute named 'StPipeline.batch_qc' in Batch QC

### ISSUE THREAD

**Issue by TaoyuJoshua** [STOmics/Stereopy#195]
I've tried the pipeline Batch QC under 0.13 and 0.14 editions, but the same problem occured
File [~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/algorithm_base.py:89](https://vscode-remote+ssh-002dremote-002b10-002e105-002e100-002e229.vscode-resource.vscode-cdn.net/home/zijin/Stereopy/~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/algorithm_base.py:89), in AlgorithmBase.get_attribute_helper(item, stereo_exp_data, res)
88 try:
---> 89     __import__(f"stereo.algorithm.{item}")
     90 except:

File [~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/__init__.py:1](https://vscode-remote+ssh-002dremote-002b10-002e105-002e100-002e229.vscode-resource.vscode-cdn.net/home/zijin/Stereopy/~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/__init__.py:1)
----> 1 from .main import BatchQc
      2 from .plot_batch_qc import ShowBatchQcReport

File [~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/main.py:4](https://vscode-remote+ssh-002dremote-002b10-002e105-002e100-002e229.vscode-resource.vscode-cdn.net/home/zijin/Stereopy/~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/main.py:4)
      3 from stereo.algorithm.algorithm_base import AlgorithmBase
----> 4 from .batchqc_raw import batchqc_raw
      6 class BatchQc(AlgorithmBase):

File [~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/batchqc_raw.py:20](https://vscode-remote+ssh-002dremote-002b10-002e105-002e100-002e229.vscode-resource.vscode-cdn.net/home/zijin/Stereopy/~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/batchqc_raw.py:20)
     19 import matplotlib
---> 20 from .test import *
     21 from .module import domain_variance_score

File [~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/test/__init__.py:11](https://vscode-remote+ssh-002dremote-002b10-002e105-002e100-002e229.vscode-resource.vscode-cdn.net/home/zijin/Stereopy/~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/test/__init__.py:11)
     10 from .distribution_fitting import distribution_fitting
---> 11 from .heatmap import sample_heatmap
     12 from .joint_plot import joint_plot
...
     93 # TODO: this may be not the best way to get sub-class
     94 # num of subclasses may be like 100-200 at most
     95 for sub_cls in AlgorithmBase.__subclasses__():

AttributeError: No attribute named 'StPipeline.batch_qc'
I'd like to know how to solve it. Thanks.

**Comment by tanliwei-coder** [comment]
Hi!! Could you give the error infomation at the bottom?

**Comment by TaoyuJoshua** [comment]
File [~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/test/__init__.py:11](https://vscode-remote+ssh-002dremote-002b10-002e105-002e100-002e229.vscode-resource.vscode-cdn.net/home/zijin/Stereopy/~/miniconda3/envs/Stereopy13/lib/python3.8/site-packages/stereo/algorithm/batch_qc/test/__init__.py:11)
     10 from .distribution_fitting import distribution_fitting
---> 11 from .heatmap import sample_heatmap
     12 from .joint_plot import joint_plot
...
     93 # TODO: this may be not the best way to get sub-class
     94 # num of subclasses may be like 100-200 at most
     95 for sub_cls in AlgorithmBase.__subclasses__():

AttributeError: No attribute named 'StPipeline.batch_qc'
I think it's the bottom

**Comment by tanliwei-coder** [comment]
@TaoyuJoshua 

I had tried to run this workflow, but never met this error, could you show me your codes?

**Comment by TaoyuJoshua** [comment]
import stereo as st
from stereo.core.ms_data import MSData
from stereo.core.ms_pipeline import slice_generator

import warnings
warnings.filterwarnings('ignore')

# prepara for input directory
data1 = st.io.read_h5ad('/home/zijin/Stereopy/Stereopy_Demo_Data/Demo_MouseEmbryo/AnnData_0.8.0/Embyro_E9.5.h5ad',bin_type='bins', bin_size=1)
data2 = st.io.read_h5ad('/home/zijin/Stereopy/Stereopy_Demo_Data/Demo_MouseEmbryo/AnnData_0.8.0/Embyro_E10.5.h5ad',bin_type='bins', bin_size=1)

# construct MSData object
ms_data = MSData(_relationship='continuous', _var_type='intersect')

ms_data += data1
ms_data += data2
ms_data.integrate()
ms_data
# preprocessing
ms_data.tl.cal_qc(scope=slice_generator[:],mode='integrate')
ms_data.tl.raw_checkpoint()

ms_data.tl.normalize_total(scope=slice_generator[:],mode='integrate')
ms_data.tl.log1p(scope=slice_generator[:],mode='integrate')
ms_data.tl.scale(scope=slice_generator[:],mode='integrate', zero_center=False, max_value=10)

# embedding
ms_data.tl.pca(scope=slice_generator[:],mode='integrate', use_highly_genes=False, n_pcs=50, res_key='pca')
ms_data.tl.neighbors(scope=slice_generator[:],mode='integrate', pca_res_key='pca', res_key='neighbors')
ms_data.tl.umap(scope=slice_generator[:],mode='integrate', pca_res_key='pca', neighbors_res_key='neighbors', res_key='umap')

# clustering
ms_data.tl.leiden(scope=slice_generator[:],mode='integrate', neighbors_res_key='neighbors', res_key='leiden')
ms_data.tl.batch_qc(scope=slice_generator[:],mode='integrate', cluster_res_key='leiden', report_path='./batch_qc', res_key='batch_qc')
Here is my code, and after running the last row, the problem occurs.

**Comment by 14MBD4** [comment]
> @TaoyuJoshua
> 
> I had tried to run this workflow, but never met this error, could you show me your codes?

Hello, I met this problem with stereopy13 too. May I ask what is your stereopy version？

**Comment by tanliwei-coder** [comment]
@TaoyuJoshua  so weird, your codes looks no problem, try to reinstall stereopy to latest version by running `pip install --force-reinstall stereopy==0.14.0b1` and run again.

**Comment by tanliwei-coder** [comment]
@14MBD4 0.14.0b1
