### ISSUE TITLE
data.tl.cell_cell_communication()

### ISSUE THREAD

**Issue by Biomamba** [STOmics/Stereopy#198]
When I run `data.tl.cell_cell_communication(
                                analysis_type='statistical',
                                cluster_res_key='leiden',
                                species='MOUSE',
                                database='cellphonedb',
                                res_key='cell_cell_communication'
                                )`.
The following error ocurred.

```
File ~/miniconda3/envs/st13/lib/python3.8/site-packages/SQLAlchemy-1.3.24-py3.8-linux-x86_64.egg/sqlalchemy/engine/strategies.py:114, in DefaultEngineStrategy.create.<locals>.connect(connection_record)
    112         if connection is not None:
    113             return connection
--> 114 return dialect.connect(*cargs, **cparams)

File ~/miniconda3/envs/st13/lib/python3.8/site-packages/SQLAlchemy-1.3.24-py3.8-linux-x86_64.egg/sqlalchemy/engine/default.py:508, in DefaultDialect.connect(self, *cargs, **cparams)
    506 def connect(self, *cargs, **cparams):
    507     # inherits the docstring from interfaces.Dialect.connect
--> 508     return self.dbapi.connect(*cargs, **cparams)

OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

my stereopy version is 0.14.0b1.
Could you please tell me how to solve it? Is there the way to pre-download the database to avoid the connect error?

**Comment by tanliwei-coder** [comment]
Did you install stereopy by conda? And also, you can download the database from [database](https://github.com/STOmics/Stereopy/tree/main/stereo/data/algorithm/cell_cell_communication/database)

**Comment by Biomamba** [comment]
> Did you install stereopy by conda? And also, you can download the database from [database](https://github.com/STOmics/Stereopy/tree/main/stereo/data/algorithm/cell_cell_communication/database)

I'm sure that I have install stereopy and the chapter before this function. Moreover, there are cellphonedb.db, liana.db, celltalkdb.db files in my device. Cloud you please tell me how to solve this problem.

**Comment by tanliwei-coder** [comment]
I never met this error, could you provide your data to me to try?
