### ISSUE TITLE
How to download the demo data in the tutorials？

### ISSUE THREAD

**Issue by suye0620** [STOmics/Stereopy#203]
stereopy所使用的demo数据集，特别是他们的原始的gef文件，如何获得？我记得暑假的时候还能用镭射传文件的软件下载，现在我找不到那个入口了。
Excuse me, where is the demo data in the tutorials？I want to get their GEF/GEM files to do some experiments.

**Comment by UglyRay7** [comment]
Download links are displayed in most tutorials. 
http://116.6.21.110:8090/share/dd965cba-7c1f-40b2-a275-0150890e005f 

Ray

**Comment by suye0620** [comment]
thanks a lot！谢谢您的分享😆发自我的 iPhone在 2023年10月20日，09:39，Longyu ***@***.***> 写道：﻿
Download links are displayed in most tutorials.
http://116.6.21.110:8090/share/dd965cba-7c1f-40b2-a275-0150890e005f
Ray
