### ISSUE TITLE
A rotation function would be quite intriguing?

### ISSUE THREAD

**Issue by Li-ZhiD** [STOmics/Stereopy#204]
Hi,
I would like to rotate the tissue at an angle, or any angle, to aid visualization and comprehension, as the current angle of tissue in the stomics chip is not unsuitable, so having a rotation function would be quite intriguing.

Thanks!

**Comment by UglyRay7** [comment]
Currently, there is not a suitable function in Stereopy to meet the requirement. You could try other tools of Stomics firstly, to address the issue. 
We will take it into the developing list!

Ray

**Comment by Li-ZhiD** [comment]
Thanks! Furthermore, Vertical and horizontal also seem to be useful.
