### ISSUE TITLE
Discrepancy between adata.X and data.exp_matrix when reading loom files using scanpy

### ISSUE THREAD

**Issue by WeipengMO** [STOmics/Stereopy#206]
I have encountered an issue when converting GEF files to loom files using the `generate_loom` function. Afterward, when I try to read the loom file into an `adata` object using scanpy, I noticed a discrepancy between the `adata.X` attribute and the `data.exp_matrix` matrix. However, the matrix within the `'matrix'` layers of the `adata` object remains consistent with the original data.

![image](https://github.com/STOmics/Stereopy/assets/7081971/80e6deeb-90e0-43c7-abd3-6be50a9cfb55)

**Comment by WeipengMO** [comment]
```
from stereo.tools import generate_loom
bgef_file = '/data/user/mowp/data/stereo-seq/Demo_MouseBrain/SS200000135TL_D1.tissue.gef'
gtf_file = '/data/user/mowp/data/stereo-seq/Demo_RNAVelocity/genes.gtf'
out_dir = '/home/mowp/test/SS200000135TL_D1_bgef/'
# generate loom file
loom_data = generate_loom(
                gef_path=bgef_file,
                gtf_path=gtf_file,
                bin_type='bins',
                bin_size=100,
                out_dir=out_dir
                )

adata_loom = sc.read_loom(loom_data)
data = st.io.read_gef(file_path=bgef_file, bin_size=100)
```

Comparing the matrix:

```
(data.exp_matrix == adata_loom.X).A.all()
```
False


```
(data.exp_matrix == adata_loom.layers['matrix']).A.all()
```
True

**Comment by Zhenbin24** [comment]
Sorry for taking so long to reply. It is recommended to use np.array_equal to compare whether the two are consistent.

`import numpy as np
np.array_equal(data.exp_matrix.todense(), adata_loom.layers['matrix'].todense())`

![image](https://github.com/STOmics/Stereopy/assets/33947214/ed8232f2-b8ba-4928-ae89-e5f2fadcc09c)

**Comment by WeipengMO** [comment]
> Sorry for replying so late,. It is recommended to use np.array_equal to compare whether the two are consistent.
> 
> `import numpy as np np.array_equal(data.exp_matrix.todense(), adata_loom.layers['matrix'].todense())`
> 
> ![image](https://private-user-images.githubusercontent.com/33947214/302072780-ed8232f2-b8ba-4928-ae89-e5f2fadcc09c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwOTgxMzcsIm5iZiI6MTcwNzA5NzgzNywicGF0aCI6Ii8zMzk0NzIxNC8zMDIwNzI3ODAtZWQ4MjMyZjItYjhiYS00OTI4LWFlODktZTVmMmZhZGNjMDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAxNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMGE2NWNhYmMwNmZhYjE5YTdjYmE1ODA5YWIwYjBlMzYzMmY0YzVmZDkyYWYzMGFlZGY0MDA5ZjcxZTY1YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KcbAKwiizqSYXeGZpotRObFNGPHztSF8q3lTuJA63oo)

Hi @Zhenbin24 , thanks for your reply.

I found out what the problem is. `adata_loom.X` is not equal to `adata_loom.layers['matrix']`. I'm wondering what is the difference between these two layers when `generate_loom` generates the loom file?    

![image](https://github.com/STOmics/Stereopy/assets/7081971/11b03fbd-4296-40d2-96ce-a0e86f8142b9)
