### ISSUE TITLE
Input data not available for CCC tutorial

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/Stereopy#210]
In Cell_Cell_Communication Tutorial (notebook)input data used is read from '../data/adata_VCM_EP.h5ad'.
Where can I find adata_VCM_EP.h5ad since it is not available in provided Stereopy_Demo_Data (http://116.6.21.110:8090/share/dd965cba-7c1f-40b2-a275-0150890e005f)?
Could you consider replacing hardcoded path with wget command that can download the input file. Also, that might be done for all tutorials. Thanks!

**Comment by UglyRay7** [comment]
We have changed the demo in this tutorial, which will be updated next version.

Ray
