### ISSUE TITLE
st.io.read_h5ad still used in Tutorials

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/Stereopy#211]
Many tutorials (e.g. [CCC](https://stereopy.readthedocs.io/en/latest/Tutorials/Cell_Cell_Communication.html)) use st.io.read_h5ad which does not exist any more (replaced with st.io.read_ann_h5ad). Please consider fixing this.

**Comment by tanliwei-coder** [comment]
On the contrary, we will plan to replace `read_ann_h5ad` to `read_h5ad`, I think you are not using the latest stereopy, please upgrade.
