### ISSUE TITLE
data.plt.ccc_circos_plot does not exist any more

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/Stereopy#212]
data.plt.ccc_circos_plot(res_key='cell_cell_communication') called in [Cell_Cell_Communication](https://stereopy.readthedocs.io/en/latest/Tutorials/Cell_Cell_Communication.html) tutorial  gives an error message: 'NoneType' object is not callable.
Is this function moved elsewhere or renamed?

**Comment by tanliwei-coder** [comment]
Which version of stereopy are you using? `ccc_circos_plot` is added on version 0.14.0b1, if it isn't, you need to reinstall to this version by specifying explicit version number because it is only a beta build.

Running command: pip install --force-reinstall stereopy==0.14.0b1
