### ISSUE TITLE
No module named 'stereo.core.ms_pipeline'

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/Stereopy#213]
In Tutorials/Time_Series_Analysis.ipynb

I'm getting an error on line:
`from stereo.core.ms_pipeline import slice_generator`

```No module named 'stereo.core.ms_pipeline' ```

**Comment by tanliwei-coder** [comment]
Upgrade stereopy to latest.

**Comment by UglyRay7** [comment]
Please install the latest version:
`pip install stereopy==0.14.0b1`
