### ISSUE TITLE
pep517 mode required

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/Stereopy#214]
I was trying to install stereopy on Ubuntu 22.04.2 LTS (Jammy Jellyfish) with:
```pip install stereopy```
But got an error requesting to use pep517 and command:
```pip install --use-pep517 stereopy```
This might be added to the installation instructions.

**Comment by tanliwei-coder** [comment]
Thanks for your feedback, we will solve this problem at next version, then you should not need to add option `--use-pep517`.

**Comment by vladimirkovacevic** [comment]
Hi guys! Sorry for bothering you again, but the issue is not yet fixed. May I ask when it will be fixed? Thanks!
