### ISSUE TITLE
Cell Segmentation.ipynb: Error: module 'torch' has no attribute 'Tensor'

### ISSUE THREAD

**Issue by vladimirkovacevic** [STOmics/Stereopy#216]
After installing all requested libraries (even thou it says: "V3 method don't need to install heavy packages like tensorflow, pytorch, you can just import cell_seg_v3 from stereo.image, ignoring the warning"): 
```
pip install tensorflow==2.7.0
pip install torch==1.10.0
pip install torchvision==0.11.1
pip install albumentations==0.4.6
```
and downloading image and model, when I start cell_seg_v3 I got an error:
```module 'torch' has no attribute 'Tensor'```

Stereopy version is 0.14.0b1. Any idea how to fix this? @tanliwei-coder

**Comment by Zhenbin24** [comment]
Hello, Can you uninstall and reinstall it? If it still doesn’t work, try setting up a new environment.
