### ISSUE TITLE
Black rectangle at the bottom of Spatial plot by using transformed seurat Rds object?

### ISSUE THREAD

**Issue by Li-ZhiD** [STOmics/Stereopy#217]
![image](https://github.com/STOmics/Stereopy/assets/31085551/a61c8a46-e97a-4587-9d52-6205f2f8f4e5)

Seurat Rds was converted by following the manual. Could anyone tell me how to remove the black region？

**Comment by OswaldZhang** [comment]
Try not to overlay your expression matrix on the image may work, at least it works for me. This is possibly due to the wrong coordinate or size of the raw image and expression matrix.

**Comment by Zhenbin24** [comment]
Hello, could you please send me the running code for review?
