### ISSUE TITLE
Convert the data from bin100 to bin50

### ISSUE THREAD

**Issue by Yungong1** [STOmics/Stereopy#221]
Hi,

Thanks so much for developing this wonderful package. Currently, I am performing the analysis on human kidney samples. l need first to use 100 bin size for structure and are identification and then perform further analysis on 50 bin size in a specific region identified by 100 bin size. I am wondering if there is any way to achieve this.

Thanks so much for your help!

**Comment by Zhenbin24** [comment]
Hello, I think you can refer to the [example ](https://stereopy.readthedocs.io/en/latest/Tutorials/High_Resolution_Export.html)here. You can export the selected area first, and then use bin50 to read the exported data.

**Comment by Yungong1** [comment]
> Hello, I think you can refer to the [example ](https://stereopy.readthedocs.io/en/latest/Tutorials/High_Resolution_Export.html)here. You can export the selected area first, and then use bin50 to read the exported data.

Thanks a lot! I will try this.

**Comment by Yungong1** [comment]
> Hello, I think you can refer to the [example ](https://stereopy.readthedocs.io/en/latest/Tutorials/High_Resolution_Export.html)here. You can export the selected area first, and then use bin50 to read the exported data.

Hi, thanks for your quick response. I think I need to extract the specific cluster in bin100 and then perform the the analysis on this cluster at the resolution of bin50. The manual selection may cause bias to the area selection. Could you please help me solve this?

Thanks so much for your patience!

**Comment by Zhenbin24** [comment]
Hello, can you filter out the data you don’t need first and then save it and then use bin50 to read it.

**Comment by Yungong1** [comment]
Got it! Thanks!
