### ISSUE TITLE
Related issues about GEF file 

### ISSUE THREAD

**Issue by ultraypy** [STOmics/Stereopy#225]
What are the meanings of geneExp, wholeExp, stat, callExp (Opt) and Attributes in the GEF file [format documentation](https://www.processon.com/view/link/610cc49c7d9c087bbd1ab7ab#map) ?
Thanks!!

**Comment by UglyRay7** [comment]
**geneExp**
![image](https://github.com/STOmics/Stereopy/assets/108983195/7e26efbc-c003-47e7-bd36-1ed427269e47)
In each binX, there are _expression_ and _gene_ two datasets that work together to record the gene expression matrix. _expression_ for (x, y, count) and _gene_ for gene information (offset, row count). They are combined with the same row index.

**wholeExp**
![image](https://github.com/STOmics/Stereopy/assets/108983195/8eaa17dc-3b30-4a7c-a198-5305048f1cb6)
In exch binX dataset, every position has been recorded, including non-expression ones. It is like a complete matrix.

**stat**
This dataset records the spatial pattern enrichment for genes.

**callExp**
This part is about the expression matrix at cellbin level, which was generated from the cell segmentation result.
