### ISSUE TITLE
ins.add_selected_area() Exception: The selected area's data cannot be empty!

### ISSUE THREAD

**Issue by UnseenAnchor** [STOmics/Stereopy#232]
<img width="611" alt="PixPin_2023-12-31_13-10-39" src="https://github.com/STOmics/Stereopy/assets/39131389/4fcbcb0d-c2f6-4e8d-b861-35830c1a0e40">

I don't know  why, I do it by the method

**Comment by tanliwei-coder** [comment]
You must click the selected area before running `ins.add_selected_area`, did you do that?

**Comment by Zhenbin24** [comment]
Hello, you can refer to this https://github.com/STOmics/Stereopy/issues/220 to see if the steps you performed are correct.
I tried it here, if done correctly there will be no problem
