### ISSUE TITLE
how E10 score is calculate?

### ISSUE THREAD

**Issue by limin321** [STOmics/Stereopy#233]
StereoMap has an E10 score: the spatial pattern enrichment score (E10) for the gene. 
1. Can anyone explain how the E10 score is calculated? 
2. what is the equation? 
3. what is the difference compared with other normalized scores?

Thanks,

**Comment by UglyRay7** [comment]
Hi, this issue part is especially for Stereopy.

E10 calculates the proportion of the gene MID counts from the top 10% (of bins with the highest MID counts) to the gene total MID counts. 
For example, when calculating **A gene** at bin100 level, sort the bins in descending order according to the MID count, perform a normal distribution on the sorted data, and take the top 10% as the enriched part of **A gene**. The final E10 score is the ratio of the enriched part to the total number of **A gene**.
The more concentrated the highly expressed regions are, the more obvious the pattern of this gene is and the stronger the enrichment.
