### ISSUE TITLE
data.tl.phenograph use error

### ISSUE THREAD

**Issue by ffZhang2003** [STOmics/Stereopy#240]
Hi,I used data.tl.phenograph `data.tl.phenograph(phenograph_k=50,pca_res_key='pca',res_key='phenograph')` on jupyterlab and  the command line,it raised an error:
jupyterlab：Kernel Restarting
The kernel for space/Untitled.ipynb appears to havedied. lt will restart automatically.
Command line: Segmentation fault
Finding 50 nearest neighbors using minkowski metric and 'auto' algorithm
OpenBLAS warning: precompiled NUM_THREADS exceeded, adding auxiliary array for thread metadata.

The server configuration is: 1T memory, 256 threads

**Comment by Zhenbin24** [comment]
Hello, this kind of situation is mostly caused by insufficient memory. You can monitor the remaining memory when running (free -h). It is recommended to try again when fewer people are using the service.
