### ISSUE TITLE
Error reading in cell binned gef file

### ISSUE THREAD

**Issue by LeonieKuechenhoff** [STOmics/Stereopy#242]
I noticed that my count matrix had random, very high values as some entries when I read in cell binned gef files with the st.io.read_gef() function. These values would change every time I read the data, so every time my count matrix was different. I believe the bug could be fixed when io.reader.py is fixed in the following way:

In read_gef() function:
line 1091: 
from:
            exp_matrix = csr_matrix((count, (cell_ind, gene_ind)), shape=(cell_num, gene_num), dtype=np.uint32)
to:
            exp_matrix = csr_matrix((count, (cell_ind, gene_ind)), shape=(cell_num, gene_num), dtype=np.uint16)

and line 1135:
from:
            exp_matrix = csr_matrix((count, indices, indptr), shape=(cell_num, gene_num), dtype=np.uint32)
to:
            exp_matrix = csr_matrix((count, indices, indptr), shape=(cell_num, gene_num), dtype=np.uint16)

**Comment by tanliwei-coder** [comment]
Thanks for your feedback, we had noticed the error you mentioned, we will fix it at next version.
