### ISSUE TITLE
Changes in expression patterns after High Resolution Matrix Export.

### ISSUE THREAD

**Issue by JungTaeKim103** [STOmics/Stereopy#243]
Hello? I have a question regarding Stereopy analysis. 
I am currently analyzing using mouse brain tissue. 
It is early in the analysis, and I am checking gene expression analysis with a file that has undergone Cell segmentation. 
I conducted stereoseq on the mouse hindbrain, but since I need a specific area, I wanted to proceed with High-Resolution Matrix Export. 
However, the gene expression pattern changed when I proceeded with the High-Resolution Export as a Cell bin.
The expression location of the target genes has changed, and the mitochondrial genes have disappeared entirely. 

What could be the problem?

![image](https://github.com/STOmics/Stereopy/assets/156797080/76f2f989-99f7-4903-9abe-b3e5ce5ae520)

**Comment by JungTaeKim103** [comment]
This is the ipynd i performed. Cell segmentation for all regions. High_Resolution_Export_cellbin for upper regions
[ipynd.zip](https://github.com/STOmics/Stereopy/files/14355813/ipynd.zip)

**Comment by maximelepetit** [comment]
Hi @JungTaeKim103  

I reopen this issue because i have the same problem ...

And there are no answer regarding this issue...

The new subset obj have count change ... the gene expression pattern changed.

Some genes that are express in the area selected before Exporting as a GEF/GEM file are disappear after the exporting ...

Same issue with the mitochondrial genes ...

Do you have any solutions ??

Maxime

**Comment by JungTaeKim103** [comment]
> Hi @JungTaeKim103
> 
> I reopen this issue because i have the same problem ...
> 
> And there are no answer regarding this issue...
> 
> The new subset obj have count change ... the gene expression pattern changed.
> 
> Some genes that are express in the area selected before Exporting as a GEF/GEM file are disappear after the exporting ...
> 
> Same issue with the mitochondrial genes ...
> 
> Do you have any solutions ??
> 
> Maxime

@maximelepetit 
Unfortunately, I have not found a solution for the expression changing after High-Resolution Export. 

However, I found that the expression does not change if I proceed with the analysis without exporting to a GEF file after selecting an area. 

This is how I have proceeded for now. 

There is a limitation that the area specified each time changes slightly, but there is no better way now.

I hope this helps
