### ISSUE TITLE
 Assistance Required in Creating Reference Samples for SingleR

### ISSUE THREAD

**Issue by JungTaeKim103** [STOmics/Stereopy#247]
Hello,

I am seeking assistance in creating reference samples for SingleR. I aim to annotate my data's cells using annotation extracted from studies with previously reported annotation details. However, I am currently unable to restructure the reference data as per the instructions provided in the tutorials.

I have been utilizing the following datasets: GSE166648_snRNA_metadata.csv.gz, GSE166648_snRNA_normdata.csv.gz, and GSE166648_snRNA_unnormdata.csv.gz, available at [NCBI GEO](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE166648).

My approach has been as follows:

1. Loading Seurat data
2. Making SummarizedExperiment
3. Conversion from Rda to h5ad
4. Following the tutorial
Could you please guide me on how to properly format the data to create a reference for SingleR?

It is my results
![image](https://github.com/STOmics/Stereopy/assets/156797080/820e826a-460a-4b7c-b814-d0b6ba4763ea)

**Comment by tanliwei-coder** [comment]
Do you mean add an existing annotation into the ref?

**Comment by JungTaeKim103** [comment]
> Do you mean you want to add an existing annotation into the reference or meet an error when using your own reference?

Hello,

I am interested in applying annotation information from other published studies to my dataset using SingleR. My goal is to leverage the annotation details reported in other research to enhance the annotations of my own cell data. However, I am facing difficulties in matching the format of my data with the reference format suggested in the SingleR tutorials.

The process I've been following involves simply loading datasets from previous studies and converting Rda files into h5ad format. Yet, it appears that this approach does not align with the reference format required by SingleR.

Could you provide guidance or a methodology on how to appropriately apply external annotation information to my dataset using SingleR? Specifically, I'm looking for a way to format the data correctly or any additional steps I might be missing to integrate the annotation information effectively.

Thank you for your help.
