### ISSUE TITLE
No module named 'stereo.image.segmentation.seg_utils'

### ISSUE THREAD

**Issue by zy-fang** [STOmics/Stereopy#248]
Tried to import and use the Tissue_Segmentation as listed in here
https://stereopy.readthedocs.io/en/latest/Tutorials/Tissue_Segmentation.html
I met this error. ModuleNotFoundError: No module named 'stereo.image.segmentation.seg_utils'
![image](https://github.com/STOmics/Stereopy/assets/47031619/7600f618-80d1-46d4-affd-215df90ee514)

However, I have installed the necessary modules and versions.

![67c7e05ecfb43e20bbbfb85aaace17e](https://github.com/STOmics/Stereopy/assets/47031619/65768174-cacd-4a6d-9907-f250fbaddbad)

**Comment by zhangyz1997** [comment]
using pypi to install stereopy instead of conda resolve the problem for me.

**Comment by zy-fang** [comment]
Yes. Thank you I try to use pypi to install stereopy. But I met a new error. 
![image](https://github.com/user-attachments/assets/3c2249d6-8606-4424-8085-3af4aea31b7a)
However, I have installed the necessary modules and versions.
