### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by eisascience** [STOmics/Stereopy#249]
LibMambaUnsatisfiableError: Encountered problems while solving:
  - package stereopy-0.5.1-py38_0 requires squidpy 1.2.2.*, but none of the providers can be installed

Could not solve for environment specs
The following package could not be installed
└─ stereopy is not installable because it requires
   └─ squidpy 1.2.2.* , which requires
      └─ scanpy >=1.8.0 , which conflicts with any installable versions previously reported.

**Comment by tanliwei-coder** [comment]
Recommend to specify the version explicitly to install stereopy: `conda install stereopy=1.1.0`.
