### ISSUE TITLE
seurat object

### ISSUE THREAD

**Issue by Carissimo** [STOmics/Stereopy#250]
Hi, 
I used your script for converting to a Seurat object, but when I use it, the 'images' slot is empty. How can I resolve this?

**Comment by eisascience** [comment]
I am surprised you actually got a Seurat Object out of their script. It keeps failing for me. I put a new issue today.. 

They should provide seurat objects by default with image in the spatial object as default in their alignment pipeline and not require a homemade custom script to be run each time for a conversion.
