### ISSUE TITLE
TypeError: base_scatter() got an unexpected keyword argument 'colors'

### ISSUE THREAD

**Issue by MingchenInSZ** [STOmics/Stereopy#259]
How to set the colors in cluster_scatter and is there any methods to set the legend by myself?  thx

**Comment by tanliwei-coder** [comment]
It is `colors` precisely, I think you are using an older version stereopy which caused this error, you can upgrade to latest.

The available values for `colors` are defined in [Colorcet Categorical](https://colorcet.holoviz.org/user_guide/Categorical.html).
