### ISSUE TITLE
When input GEM at cell level(Cell bins), there is no dnbCount, cell area and cell border information.

### ISSUE THREAD

**Issue by JYWANG-UCAS** [STOmics/Stereopy#260]
Hi, I input Gem file at cell bin level, and I couldn't find cell area and cell border information.
**packages : stereopy   1.1.0**
![1711899337986](https://github.com/STOmics/Stereopy/assets/67094691/84c13f32-aa67-4317-ba69-58dfc3255edb)

![1711899292445](https://github.com/STOmics/Stereopy/assets/67094691/97094317-85d3-4c9a-a731-03332b079332)

![1711899366240](https://github.com/STOmics/Stereopy/assets/67094691/7fa504ad-e744-42aa-8078-16a5df6138c6)

**Comment by JYWANG-UCAS** [comment]
Is there a solution?
Thank you

**Comment by tanliwei-coder** [comment]
Only GEF has those infomation but GEM doesn't.
