### ISSUE TITLE
Stereopy input (cellbin)

### ISSUE THREAD

**Issue by maximelepetit** [STOmics/Stereopy#262]
Hello,

I have a question about input of stereopy.
I ran successfully the stereoPipeline_v7.1 pipeline with cellbin.

Now, I want run the Quick Start (cellbin) tutorial.

Which input should I use between adjusted.cellbin.gef and cellbin.gef ?

Thanks for help!

**Comment by tanliwei-coder** [comment]
I guess stereoPipeline_v7.1 is a pipeline containing Cell-Correction function, `adjusted.cellbin.gef` is the corrected GEF, so, generally, we should use `adjusted.cellbin.gef` to do subsequent analysis.

**Comment by maximelepetit** [comment]
Thanks a lot for the reply
