### ISSUE TITLE
update documentation

### ISSUE THREAD

**Issue by maximelepetit** [STOmics/Stereopy#266]
Hi ,

I notice few mistakes browsing the documentation : 

- First i don't find in the API , the reference of **stereo.core.StPipeline.filter_marker_genes()** this function is use in the code cell [35] of Cellbin quickstart notebook and code cell [37] in Squarebin quickstart tutorial.

- Also in the api, in the stereo.core.StPipeline.find_marker_genes documentation function, for the corr_method parameter, as default it's set as 'benjamini-hochberg'. It is written as explication of this parameter (corr_method) : _corr_method (str) – correlation method._ . I think you want to mean _pvalue correction method_ instead of _correlation method_ ? And it missing the different values that this parameter can take.

- In the tutorial of SingleR : https://stereopy.readthedocs.io/en/latest/Tutorials/SingleR.html#Annotation-after-clutering, there's a spelling mistake regarding "Annotation-after-clutering", i think you miss the "s" of clustering :)

Thanks !

**Comment by tanliwei-coder** [comment]
Thanks for you feedback, we will update on next version.
