### ISSUE TITLE
Notebook problems with version 1.2.0

### ISSUE THREAD

**Issue by robin-sto** [STOmics/Stereopy#273]
[stereopy.txt](https://github.com/STOmics/Stereopy/files/15223913/stereopy.txt)

Hello,

We are getting errors using jupyter lab with version 1.2.0.  Please let me know how to address these two errors:

[W 11:43:10.530 LabApp] Failed validating settings (@jupyterlab/filebrowser-extension:browser): Additional properties are not allowed ('showFullPath', 'sortNotebooksFirst', 'showFileCheckboxes', 'showFileSizeColumn' were unexpected)
    
    Failed validating 'additionalProperties' in schema:
        {'additionalProperties': False,
         'description': 'File Browser settings.',
         'jupyter.lab.setting-icon': 'ui-components:folder',
         'jupyter.lab.setting-icon-label': 'File Browser',
         'jupyter.lab.shortcuts': [{'command': 'filebrowser:create-main-launcher',
                                    'keys': ['Accel Shift L'],
                                    'selector': 'body'}, ...

[W 11:43:10.726 LabApp] 500 GET /api/nbconvert?1715010190682 (10.200.10.247): Could not import nbconvert: cannot import name 'contextfilter' from 'jinja2' (/usr/local/anaconda3-2020/lib/python3.8/site-packages/jinja2/__init__.py)
[W 11:43:10.727 LabApp] Could not import nbconvert: cannot import name 'contextfilter' from 'jinja2' (/usr/local/anaconda3-2020/lib/python3.8/site-packages/jinja2/__init__.py)

Attached are conda and pip list

Thank you

**Comment by tanliwei-coder** [comment]
It may be caused by conflict between jinja2 and jupyter-notebook, I suggest you install jupyter-notebook and stereopy in different conda enviroment to avoid some unpredictable sofware confilcts.
