### ISSUE TITLE
Subsampling

### ISSUE THREAD

**Issue by BioRB** [STOmics/Stereopy#277]
hello, do you know if would be possible to obtain a subsample (randomly) from the original gef?

**Comment by tanliwei-genomics-cn** [comment]
you can sample the `data.cells.cell_name` randomly to get a cell_name_subset, and then run `data_subset = data.tl.filter_cells(cell_list=cell_name_subset, inplace=False)` to get a subsample data, this is done on cells/bins, similarly, you can do on genes through `data.genes.gene_name` and `data.tl.filter_genes()`.
