### ISSUE TITLE
extract expresison matrix from H5MS

### ISSUE THREAD

**Issue by BioRB** [STOmics/Stereopy#281]
Hello, I need to extract the expression matrix for 1 sample from a H5MS file that includes 12 samples (slices), to perform downstream analysis.
I need to extract just the expression matrix with cluster information for one slice from the H5ms.
Alternativelly I need to directily generate an h5ad for just one sample from the h5ms file. 
would you help me to do that using Stereopy?
thanks
RB

**Comment by tanliwei-genomics-cn** [comment]
Was the cluster you want to extract generated by using Stereopy to analyse?
