### ISSUE TITLE
update error when download the requirements for stereopy 1.3.0

### ISSUE THREAD

**Issue by Mr-grasscarp** [STOmics/Stereopy#290]
I want to try the latest version of stereopy, but after I created a new env with python 3.8, the requirements of the software met some error. Some packages require python 3.9 or 3.10，and gefpy have no 1.16 version.
ERROR: Ignored the following versions that require a different python version: 1.11.0 Requires-Python <3.13,>=3.9; 1.11.0rc1 Requires-Python <3.13,>=3.9; 1.11.0rc2 Requires-Python <3.13,>=3.9; 1.11.1 Requires-Python <3.13,>=3.9; 1.11.2 Requires-Python <3.13,>=3.9; 1.11.3 Requires-Python <3.13,>=3.9; 1.11.4 Requires-Python >=3.9; 1.12.0 Requires-Python >=3.9; 1.12.0rc1 Requires-Python >=3.9; 1.12.0rc2 Requires-Python >=3.9; 1.13.0 Requires-Python >=3.9; 1.13.0rc1 Requires-Python >=3.9; 1.13.1 Requires-Python >=3.9; 1.14.0rc1 Requires-Python >=3.10; 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9; 1.26.1 Requires-Python <3.13,>=3.9; 1.26.2 Requires-Python >=3.9; 1.26.3 Requires-Python >=3.9; 1.26.4 Requires-Python >=3.9; 2.0.0b1 Requires-Python >=3.9; 2.0.0rc1 Requires-Python >=3.9; 2.0.0rc2 Requires-Python >=3.9; 2.1.0 Requires-Python >=3.9; 2.1.0rc0 Requires-Python >=3.9; 2.1.1 Requires-Python >=3.9; 2.1.2 Requires-Python >=3.9; 2.1.3 Requires-Python >=3.9; 2.1.4 Requires-Python >=3.9; 2.2.0 Requires-Python >=3.9; 2.2.0rc0 Requires-Python >=3.9; 2.2.1 Requires-Python >=3.9; 2.2.2 Requires-Python >=3.9; 2023.10.0 Requires-Python >=3.9; 2023.10.1 Requires-Python >=3.9; 2023.11.0 Requires-Python >=3.9; 2023.12.0 Requires-Python >=3.9; 2023.12.1 Requires-Python >=3.9; 2023.5.1 Requires-Python >=3.9; 2023.6.0 Requires-Python >=3.9; 2023.6.1 Requires-Python >=3.9; 2023.7.0 Requires-Python >=3.9; 2023.7.1 Requires-Python >=3.9; 2023.8.0 Requires-Python >=3.9; 2023.8.1 Requires-Python >=3.9; 2023.9.0 Requires-Python >=3.9; 2023.9.1 Requires-Python >=3.9; 2023.9.2 Requires-Python >=3.9; 2023.9.3 Requires-Python >=3.9; 2024.1.0 Requires-Python >=3.9; 2024.1.1 Requires-Python >=3.9; 2024.2.0 Requires-Python >=3.9; 2024.2.1 Requires-Python >=3.9; 2024.3.0 Requires-Python >=3.9; 2024.3.1 Requires-Python >=3.9; 2024.4.0 Requires-Python >=3.9; 2024.4.1 Requires-Python >=3.9; 2024.4.2 Requires-Python >=3.9; 2024.5.0 Requires-Python >=3.9; 2024.5.1 Requires-Python >=3.9; 2024.5.2 Requires-Python >=3.9; 3.2.0 Requires-Python >=3.9; 3.2.0.dev1 Requires-Python >=3.9; 3.2.0.dev2 Requires-Python >=3.9; 3.2.0.dev3 Requires-Python >=3.9; 3.2.0.dev4 Requires-Python >=3.9; 3.2.0rc1 Requires-Python >=3.9; 3.2.0rc2 Requires-Python >=3.9; 3.2.0rc3 Requires-Python >=3.9; 3.2.1 Requires-Python >=3.9; 3.2.2 Requires-Python >=3.9; 3.2.2rc1 Requires-Python >=3.9; 3.3.0 Requires-Python >=3.9; 3.3.0.dev1 Requires-Python >=3.9; 3.3.0.dev2 Requires-Python >=3.9; 3.3.0.dev3 Requires-Python >=3.9; 3.3.0rc1 Requires-Python >=3.9; 3.3.0rc2 Requires-Python >=3.9; 3.3.0rc3 Requires-Python >=3.9; 3.3.1 Requires-Python >=3.9; 3.3.1.dev1 Requires-Python >=3.9; 3.3.1rc1 Requires-Python >=3.9; 3.3.2 Requires-Python >=3.9; 3.3.3 Requires-Python >=3.9; 3.3.4 Requires-Python >=3.9; 3.3.4rc1 Requires-Python >=3.9; 3.4.0 Requires-Python >=3.9; 3.4.0.dev1 Requires-Python >=3.9; 3.4.0.dev2 Requires-Python >=3.9; 3.4.0.dev3 Requires-Python >=3.9; 3.4.0.dev4 Requires-Python >=3.9; 3.4.0.dev5 Requires-Python >=3.9; 3.4.0.dev6 Requires-Python >=3.9; 3.4.0.dev7 Requires-Python >=3.9; 3.4.0.dev8 Requires-Python >=3.9; 3.4.0rc1 Requires-Python >=3.9; 3.4.0rc2 Requires-Python >=3.9; 3.4.1 Requires-Python >=3.9; 3.5.0.dev1 Requires-Python >=3.10; 3.5.0.dev3 Requires-Python >=3.10; 3.5.0.dev4 Requires-Python >=3.10; 3.5.0.dev5 Requires-Python >=3.10; 3.8.0 Requires-Python >=3.9; 3.8.0rc1 Requires-Python >=3.9; 3.8.1 Requires-Python >=3.9; 3.8.2 Requires-Python >=3.9; 3.8.3 Requires-Python >=3.9; 3.8.4 Requires-Python >=3.9; 3.9.0 Requires-Python >=3.9; 3.9.0rc2 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement gefpy>=1.1.6 (from versions: 0.1.2, 0.6.9, 0.6.12, 0.6.14, 0.6.17, 0.6.18, 0.6.23, 0.6.24, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.7.10, 0.7.11, 0.7.12, 0.7.14, 1.0.0, 1.1.0, 1.1.1, 1.1.2, 1.1.3)
ERROR: No matching distribution found for gefpy>=1.1.6

**Comment by tanliwei-genomics-cn** [comment]
This error commonly is caused by a wrong version python, Did you switch to the new environment you created with py38?

**Comment by Mr-grasscarp** [comment]
The environment is right. After I changed the requirement document to require gefpy≥1.13，the software can be installed correctly.
