### ISSUE TITLE
problem with singleR

### ISSUE THREAD

**Issue by ultraypy** [STOmics/Stereopy#291]
![image](https://github.com/STOmics/Stereopy/assets/56919476/8cb6cde4-38e5-4b6b-971b-e48fc6b0d33f)

a problem occured when use singler to do annotation.
https://stereopy.readthedocs.io/en/latest/_modules/stereo/algorithm/single_r/single_r.html

**Comment by tanliwei-genomics-cn** [comment]
Was the key **ClusterHomeostasis** specified by parameter `ref_use_col` in obs? print the `data.cells` to check it.
