### ISSUE TITLE
stereopy fiter_cell() 的参数和说明文档让人很费解，希望可以更正一下

### ISSUE THREAD

**Issue by vanhzh7909** [STOmics/Stereopy#295]
作者好，

如题，里面的参数命名和说明让人很费解，希望能修改下。

非常感谢

![image](https://github.com/STOmics/Stereopy/assets/148750814/e4071e2a-94f6-4a43-b8da-ae09edeafb66)
![image](https://github.com/STOmics/Stereopy/assets/148750814/1d051ea0-d6cb-4b17-87ec-aac07bc80b29)

**Comment by tanliwei-genomics-cn** [comment]
在参数命名上的确存在歧义，我们会在下一个版本更改参数的命名，谢谢反馈！
