### ISSUE TITLE
Met typeError when following quick start（multi-sample）

### ISSUE THREAD

**Issue by Mr-grasscarp** [STOmics/Stereopy#299]
After integration, I met the following error when I tried to conduct quality control.
`ms_data.tl.cal_qc(scope=slice_generator[:],mode='integrate')`
`ms_data`

TypeError                                 Traceback (most recent call last)
Cell In[42], line 1
----> 1 ms_data.tl.cal_qc(scope=slice_generator[:],mode='integrate')
      2 ms_data

File C:\ProgramData\anaconda3\envs\st\lib\site-packages\stereopy-1.3.0-py3.8.egg\stereo\core\ms_pipeline.py:266, in MSDataPipeLine.__getattr__.<locals>.temp(*args, **kwargs)
    263     kwargs["mode"] = self.__mode
    265 if kwargs["mode"] == "integrate":
--> 266     return self._use_integrate_method(item, *args, **kwargs)
    267 elif kwargs["mode"] == "isolated":
    268     self._run_isolated_method(item, *args, **kwargs)

File C:\ProgramData\anaconda3\envs\st\lib\site-packages\stereopy-1.3.0-py3.8.egg\stereo\core\ms_pipeline.py:107, in MSDataPipeLine._use_integrate_method(self, item, *args, **kwargs)
    104     ms_data_view = self.ms_data[scope]
    106 scope_key = self.ms_data.generate_scope_key(ms_data_view._names)
--> 107 self.ms_data.scopes_data[scope_key] = ms_data_view.merged_data
    109 # def callback_func(key, value):
    110 #     # key_name = "scope_[" + ",".join(
    111 #     #     [str(self.ms_data._names.index(name)) for name in ms_data_view._names]) + "]"
   (...)
    147 
    148 # ms_data_view._merged_data.tl.reset_key_record = reset_key_record
    150 new_attr = self.__class__.BASE_CLASS.__dict__.get(item, None)

TypeError: unhashable type: 'list'

**Comment by tanliwei-genomics-cn** [comment]
Please show me all your codes.

**Comment by Mr-grasscarp** [comment]
import sys
import os
from natsort import natsorted
import stereo as st
from stereo.core.ms_data import MSData
from stereo.core.ms_pipeline import slice_generator

import warnings
warnings.filterwarnings('ignore')

# prepara for input directory
data_dir = r'D:\devLr\bestsamples'

data_list=[]
for fn in os.listdir(data_dir):
    data_list.append(os.path.join(data_dir, fn))

# ensure data order by naming them regularly
data_list = natsorted(data_list)

# construct MSData object
ms_data = MSData(_relationship='other', _var_type='intersect')

# when come to loaded data object
# ms_data = MSData(_data_list=[data1, data2], _names=['s1', 's2'], _relationship='other', _var_type='intersect')

# add all samples into MSData
for sample in data_list:
    ms_data += st.io.read_gef(file_path=sample, bin_type='bins', bin_size=15)

ms_data.relationship='ts'

ms_data.integrate()

ms_data.tl.cal_qc(scope=slice_generator[:],mode='integrate')
-----------------------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 ms_data.tl.cal_qc(scope=slice_generator[:],mode='integrate')
      2 ms_data

File C:\ProgramData\anaconda3\envs\st\lib\site-packages\stereopy-1.3.0-py3.8.egg\stereo\core\ms_pipeline.py:266, in MSDataPipeLine.__getattr__.<locals>.temp(*args, **kwargs)
    263     kwargs["mode"] = self.__mode
    265 if kwargs["mode"] == "integrate":
--> 266     return self._use_integrate_method(item, *args, **kwargs)
    267 elif kwargs["mode"] == "isolated":
    268     self._run_isolated_method(item, *args, **kwargs)

File C:\ProgramData\anaconda3\envs\st\lib\site-packages\stereopy-1.3.0-py3.8.egg\stereo\core\ms_pipeline.py:107, in MSDataPipeLine._use_integrate_method(self, item, *args, **kwargs)
    104     ms_data_view = self.ms_data[scope]
    106 scope_key = self.ms_data.generate_scope_key(ms_data_view._names)
--> 107 self.ms_data.scopes_data[scope_key] = ms_data_view.merged_data
    109 # def callback_func(key, value):
    110 #     # key_name = "scope_[" + ",".join(
    111 #     #     [str(self.ms_data._names.index(name)) for name in ms_data_view._names]) + "]"
   (...)
    147 
    148 # ms_data_view._merged_data.tl.reset_key_record = reset_key_record
    150 new_attr = self.__class__.BASE_CLASS.__dict__.get(item, None)

TypeError: unhashable type: 'list'

**Comment by tanliwei-genomics-cn** [comment]
I note that there was a line `ms_data.relationship='ts'` in your codes, it should raise an **Exception** beacuse the available values of `relationship` only include **['continuous', 'time_series', 'other']**, but not in your codes, that is so weird, except for this line, your codes look no problem, I commented this line and try the codes with my data, there were also no errors you met, I am so sorry for that I can not find the reason about that.

**Comment by Mr-grasscarp** [comment]
It's really strange, these codes can run normally in stereopy 1.2.0.

**Comment by tanliwei-genomics-cn** [comment]
You can try creating a new conda evironment from scratch and installing the latest stereopy(don't install any other sofwares) to see if you still meet this error.

**Comment by tanliwei-coder** [comment]
Sorry, that is an error about jupyter notebook, I don't know the reason, you can try to install notebook first and then install stereopy to see if the error is eliminated.
