### ISSUE TITLE
Met AttributeError when doing batchqc

### ISSUE THREAD

**Issue by Mr-grasscarp** [STOmics/Stereopy#300]
Hello!I met an AttributeError when doing batchqc with stereopy v1.2.0 or v1.3.0.
`AttributeError: No attribute named 'StPipeline.batch_qc'`

**Comment by tanliwei-genomics-cn** [comment]
Did you run it in a python script named as **batch_qc.py**? If so, change the file name to other.

**Comment by Mr-grasscarp** [comment]
I ran it with jupyter notebook and the bug still persists  no matter how I change the name.

**Comment by Mr-grasscarp** [comment]
the version of setuptools is 69.5.1



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月1日(星期一) 下午4:00
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [STOmics/Stereopy] Met AttributeError when doing batchqc (Issue #300)














 
Check if the version of setuptools is higher than 69.5.1, if so, downgrade to this version.

**Comment by tanliwei-genomics-cn** [comment]
Sorry that I forgot something to tell you the **torch** must be installed, you can to install some others necessary dependencies mentioned in [requirements_for_image.txt](https://github.com/STOmics/Stereopy/blob/main/requirements_for_image.txt).
