### ISSUE TITLE
Compatibility with newer Python versions

### ISSUE THREAD

**Issue by scseeman** [STOmics/Stereopy#301]
Are there plans to make Stereopy compatible with Python versions newer than 3.8? I run into a lot of difficulties installing and using Stereopy with other python packages that expect newer versions of Python. Python 3.8 is expected to be unsupported by the end of this year. Thanks

**Comment by tanliwei-genomics-cn** [comment]
That is already in our consideration, but not any time soon, it involves some other dependencies that need to be adapted.
