### ISSUE TITLE
single R gpu error

### ISSUE THREAD

**Issue by solivehong** [STOmics/Stereopy#302]
i have error for singleR GPU method 
it need libcugraph
conda install :  rapid or libcugraph but  version is not compatible, how should I do it

**Comment by tanliwei-genomics-cn** [comment]
Did you create your conda environment following the gide [Clustering by GPU](https://stereopy.readthedocs.io/en/latest/Tutorials/Clustering_by_GPU.html).

**Comment by ultraypy** [comment]
singler does not work well on some data, manual annotation is recommended
