### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by tenlives** [STOmics/Stereopy#303]
![1720251567726](https://github.com/STOmics/Stereopy/assets/44781595/aa8903e8-0ea2-45f9-b8c1-22aa333bbe9e)

Hi, I used the latest version 1.3.1, it raises the error above. 
Could you help me deal with it? thank you !

**Comment by tanliwei-coder** [comment]
I didn't meet this error in 1.3.1, could you show me all your codes?
