### ISSUE TITLE
real_gene_name is lost after merging two gef file

### ISSUE THREAD

**Issue by zzhongzz** [STOmics/Stereopy#308]
When I use `st.io.read_gef` to read a gef file, there is a `genes` attribute and under which there are `gene_name` and `real_gene_name`. The `gene_name` is actually Ensembl gene ID like 'ENSG00000000003' while the `real_gene_name` is gene symbol like 'TSPAN6'.

However, when I merge two gef file using `MSData`, the `real_gene_name` under `ms_data.merged_data.genes` becomes None.
 
Is this a bug or a feature? How can I get the gene symbols back?

**Comment by tanliwei-coder** [comment]
Sorry, that is a bug, if you don't need the `geneID`, you can set the parameter `gene_name_index` to True when reading data via `st.io.read_gef`, the gene symbols will be used as `gene_name` under the attribute `gene`.

**Comment by zzhongzz** [comment]
I'm using 1.3.1 but still have this bug

**Comment by tanliwei-coder** [comment]
> I'm using 1.3.1 but still have this bug

Sorry, that is a bug, if you don't need the geneID, you can set the parameter gene_name_index to True to set gene symbols as gene_name which is under the genes attribute.

**Comment by zzhongzz** [comment]
Thank you for your clarification. Unfortunately I need both gene ID and gene symbol. Do you have any plan to fix it?

**Comment by tanliwei-coder** [comment]
A new version will be released around the end of August, currently, you can do like the following codes to solve this problem

```
for data in ms_data.data_list:
    ms_data.merged_data.genes.var['real_gene_name'] = data.genes.var['real_gene_name']
```

**Comment by zzhongzz** [comment]
> A new version will be released around the end of August, currently, you can do like the following codes to solve this problem
> 
> ```
> for data in ms_data.data_list:
>     ms_data.merged_data.genes.var['real_gene_name'] = data.genes.var['real_gene_name']
> ```

Adding these lines after `ms_data.integrate()` solves my problem, thank you!
