### ISSUE TITLE
New docker image for stereopy version 1.3.1

### ISSUE THREAD

**Issue by dr8k8n8wk** [STOmics/Stereopy#309]
Hi stereopy team,

I’m a Mac user so have to use Docker to run your software. I noticed that version 1.3.1 is out with some great updates, but I can’t find an updated Docker image for it. Is it possible to share one?

Thanks for your help!

**Comment by tanliwei-coder** [comment]
Sorry, we do not release docker images for any version of stereopy, you may need to create by yourself.
