### ISSUE TITLE
write_h5ms error 

### ISSUE THREAD

**Issue by pmf816** [STOmics/Stereopy#310]
I referred to the online tutorial (https://stereopy.readthedocs.io/en/latest/Tutorials%28Multi-sample%29/Batch_Effect.html) to integrate spatial transcriptomics data from multiple sections of one sample (.h5ad), and everything was fine, but I encountered an error when saving as .h5ms. At the same time, I have confirmed that there are no files with the same name in the folder. The version of Stereopy is 1.3.0.

import sys
import os
import seaborn as sns
import stereo as st
from natsort import natsorted
from matplotlib import pyplot as plt
from stereo.core.ms_data import MSData
from stereo.core.ms_pipeline import slice_generator
%matplotlib notebook
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

data_dir = '/home/bin50/mouse2/data'

data_list=[]
for fn in os.listdir(data_dir):
  data_list.append(os.path.join(data_dir, fn))

# ensure data order by naming them regularly
data_list = natsorted(data_list)

# construct MSData object
ms_data = MSData(_relationship='other', _var_type='intersect')

# when come to loaded data object
# ms_data = MSData(_data_list=[data1, data2], _names=['s1', 's2'], _relationship='other', _var_type='intersect')

##### add all samples into MSData #####
for sample in data_list:
  ms_data += st.io.read_h5ad(file_path=sample, 
                             bin_type='bins', 
                             bin_size=50 
  )

st.io.write_h5ms(ms_data,output='test.h5ms')

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5d.pyx:135, in h5py.h5d.create()

ValueError: Unable to create dataset (name already exists)

![截屏2024-07-26 上午9 54 32](https://github.com/user-attachments/assets/4a6c01d2-bffa-4cdd-8bd6-94c7d2bd4059)

**Comment by tanliwei-coder** [comment]
That did not mean there is a same name of file, it may have same name of items in the data read from your file, but the error information you provided is too few to find the reason, could you post all the error messages here? If possible, providing your files with me is better.

**Comment by pmf816** [comment]
Thanks, here is all the error information, and my input data is named as follows: T01.h5ad-T15.h5ad.

**Comment by pmf816** [comment]
Thanks, here is all the error information, and my input data is named as follows: T01.h5ad-T15.h5ad.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[22], line 1
----> 1 st.io.write_h5ms(ms_data,output='test.h5ms')

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/stereo/io/writer.py:304, in write_h5ms(ms_data, output)
    302 for idx, data in enumerate(ms_data._data_list):
    303     f['sample'].create_group(f'sample_{idx}')
--> 304     _write_one_h5ad(f['sample'][f'sample_{idx}'], data, use_raw=True, use_result=True)
    305     # if isinstance(data, AnnBasedStereoExpData):
    306     #     _write_one_anndata(f['sample'][f'sample_{idx}'], data)
    307     # else:
   (...)
    310 #     f.create_group('sample_merged')
    311 #     _write_one_h5ad(f['sample_merged'], ms_data._merged_data)
    312 if len(ms_data.scopes_data) > 0:

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/stereo/io/writer.py:109, in _write_one_h5ad(f, data, use_raw, use_result, key_record)
    107         sn_data = pd.DataFrame(sn_list, columns=['batch', 'sn'])
    108         h5ad.write(sn_data, f, 'sn', save_as_matrix=True)
--> 109 h5ad.write(data.genes, f, 'genes')
    110 h5ad.write(data.cells, f, 'cells')
    111 if data.position_z is None:

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/functools.py:875, in singledispatch.<locals>.wrapper(*args, **kw)
    871 if not args:
    872     raise TypeError(f'{funcname} requires at least '
    873                     '1 positional argument')
--> 875 return dispatch(args[0].__class__)(*args, **kw)

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/stereo/io/h5ad.py:58, in _(v, f, k)
     56 @write.register(Gene)
     57 def _(v, f, k):
---> 58     write_genes(f, k, v)

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/stereo/io/h5ad.py:117, in write_genes(f, k, v, dataset_kwargs)
    115 g.attrs['encoding-type'] = 'gene'
    116 g.attrs['version'] = 'v2'
--> 117 write_dataframe(g, 'var', v.to_df(), dataset_kwargs)

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/stereo/io/h5ad.py:176, in write_dataframe(f, key, df, dataset_kwargs, save_as_matrix)
    174 else:
    175     for col_name, (_, series) in zip(col_names, df.items()):
--> 176         write_series(group, col_name, series, dataset_kwargs=dataset_kwargs)

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/stereo/io/h5ad.py:182, in write_series(group, key, series, dataset_kwargs)
    179 def write_series(group, key, series, dataset_kwargs=MappingProxyType({})):
    180     # group here is an h5py type, otherwise categoricals won’t write
    181     if series.dtype == object:  # Assuming it’s string
--> 182         group.create_dataset(
    183             key,
    184             data=series.values,
    185             dtype=h5py.special_dtype(vlen=str),
    186             **dataset_kwargs,
    187         )
    188     elif is_categorical_dtype(series):
    189         # This should work for categorical Index and Series
    190         categorical: pd.Categorical = series.values

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/h5py/_hl/group.py:183, in Group.create_dataset(self, name, shape, dtype, data, **kwds)
    180         parent_path, name = name.rsplit(b'/', 1)
    181         group = self.require_group(parent_path)
--> 183 dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
    184 dset = dataset.Dataset(dsid)
    185 return dset

File /data/pxd/miniconda3/envs/py3.8/lib/python3.8/site-packages/h5py/_hl/dataset.py:165, in make_new_dset(parent, shape, dtype, data, name, chunks, compression, shuffle, fletcher32, maxshape, compression_opts, fillvalue, scaleoffset, track_times, external, track_order, dcpl, dapl, efile_prefix, virtual_prefix, allow_unknown_filter, rdcc_nslots, rdcc_nbytes, rdcc_w0)
    162 else:
    163     sid = h5s.create_simple(shape, maxshape)
--> 165 dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
    167 if (data is not None) and (not isinstance(data, Empty)):
    168     dset_id.write(h5s.ALL, h5s.ALL, data)

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5d.pyx:135, in h5py.h5d.create()

ValueError: Unable to create dataset (name already exists)

**Comment by tanliwei-coder** [comment]
The error may occur on one of your files, running `st.io.write_h5ad` for each file to find the file where the error occur, then print the `data.genes` of the error file and post here.

**Comment by pmf816** [comment]
Thank you for your advice. I have iterated through all the input .h5ad files as follows: data = st.io.read_h5ad(input_file, flavor='scanpy', bin_type='bins', bin_size=50, spatial_key='spatial'), and running st.io.write_h5ad to write the files. Unfortunately, each file still results in the same error message mentioned earlier.

The data.genes for one of the files is as follows (eg.)

By the way, using the command adata = st.io.stereo_to_anndata(data, output='./scanpy_anndata.h5ad') successfully saves the data. Is there a similar method to save the integrated data as anndata?

Additionally, there is no image data in the .uns of the data, does this mean that it is not possible to visualize the spatial gene expression through Scanpy (sc.pl.spatial)?

**Comment by pmf816** [comment]
Thank you for your advice. 

I have iterated through all the input .h5ad files as follows: data = st.io.read_h5ad(input_file, flavor='scanpy', bin_type='bins', bin_size=50, spatial_key='spatial'), and running st.io.write_h5ad to write the files. Unfortunately, each file still occur the same error.
![stereo-error](https://github.com/user-attachments/assets/bc6098f5-a3a4-4f29-80ed-d912d668f178)

The data.genes for one of the files is as follows (eg.)
![截屏2024-08-05 上午11 29 18](https://github.com/user-attachments/assets/fe14130b-2fb0-4c3d-9989-a888a1aaa23d)

By the way, using the command adata = st.io.stereo_to_anndata(data, output='./scanpy_anndata.h5ad') successfully saves the data. Is there a similar method to save the integrated data as anndata?

Additionally, there is no image data in the .uns of the data, does this mean that it is not possible to visualize the spatial gene expression through Scanpy (sc.pl.spatial)?
![截屏2024-08-05 上午11 29 55](https://github.com/user-attachments/assets/b58a0fb8-1f38-431a-8a1d-251a2bd3bb2b)

**Comment by tanliwei-coder** [comment]
I have known the cause of the error, the name of `index` of the `data.genes` is dumplicate with one of its columns, before creating `MSData`, running `data.adata.var.index = None` for each data object can solve your problem.

**Comment by pmf816** [comment]
Thank you for your reply, it has resolved my issue. By the way, "data.adata.var.index.name = None" works for me.
