### ISSUE TITLE
coloring spatial featureplot

### ISSUE THREAD

**Issue by TdzBAS** [STOmics/Stereopy#311]
Hi together,

thanks for this amazing tool.
Is it possible to color the spatial featureplot like this? 
![image](https://github.com/user-attachments/assets/bcbe442e-926e-4033-be8a-10cd9975a7ec)

I dont like the yellow background like here:
![image](https://github.com/user-attachments/assets/0ac2f5c1-994a-4928-8912-c8cb397af793)

Best,
Tolga

**Comment by tanliwei-coder** [comment]
Sorry, no images in your issue.

**Comment by tanliwei-coder** [comment]
I think reversing the colorbar by setting parameter `color_bar_reverse` to True can achive your purpose.
