### ISSUE TITLE
Figure object

### ISSUE THREAD

**Issue by benben-miao** [STOmics/Stereopy#313]
How can I get the image object of matplotlib for the panel.Column object returned by the current data.plt.violin()? And why does Column().objects not contain image objects but display images in notebook? How to get image objects?

**Comment by tanliwei-coder** [comment]
The `panel.Column` only contains the `InputText` widgets you see on notebook, the figure is not returned and is diplayed directly, what is your purpose of getting the figure object? if you want to save the figure, you can specify the save path by parameter `out_path`
