### ISSUE TITLE
Fails to read in h5ad object created manually from seurat into stereoexpdata object

### ISSUE THREAD

**Issue by TdzBAS** [STOmics/Stereopy#314]
Hi,

I have created an anndataobject manually from an seuratobject, and it works for all of my python downstream analysis.
![image](https://github.com/user-attachments/assets/d50ab8b9-e42b-4377-b328-1557bd44a64a)
But I cant read it into a stereoexp data object, so that I can run spatial hotspot for instance. It says that the result object is empty.

![image](https://github.com/user-attachments/assets/2c899a3a-4fe4-4137-bc5b-843bc4e8fb68)
![image](https://github.com/user-attachments/assets/380ae13b-c81c-44d3-b325-251a9093d98c)
![image](https://github.com/user-attachments/assets/ea27223b-fcee-4bb2-ad52-2537fab32b9e)

could you help me here?

Best,
T

**Comment by tanliwei-coder** [comment]
use [st.io.read_h5ad](https://stereopy.readthedocs.io/en/latest/content/stereo.io.read_h5ad.html)

**Comment by TdzBAS** [comment]
I still get the same error @tanliwei-coder

**Comment by tanliwei-coder** [comment]
Stereopy currently only can use the hvg result calculated by itself, if you want to use an existing hvg result, you can use stereopy built-in method to run `Highly variable genes` firstly and then use the existing hvg result to  overwirte the `data.genes.var['highly_variable']`.
