### ISSUE TITLE
Feature request: add "layers" in StereoExpData to enable find_marker_genes to use normalized data

### ISSUE THREAD

**Issue by zzhongzz** [STOmics/Stereopy#316]
When analyzing spatial data, the common practice using stereopy pipeline is like this:
```
data = st.io.read_gef(gef_file, bin_size=bin_size)
data.tl.cal_qc()
data.tl.filter_cells(min_gene=1)
data.tl.raw_checkpoint()
data.tl.normalize_total()
data.tl.log1p()
data.tl.highly_variable_genes()
data.tl.scale()
data.tl.pca()
data.tl.neighbors()
data.tl.leiden()
...
```
Which runs `data.tl.raw_checkpoint()` after filtering genes and cells, then run `data.tl.normalize_total()` and `data.tl.log1p()` and `data.tl.scale()` before clustering. 

## Problem
If I need to find marker genes for each cluster, then there is a dilemma, `find_marker_genes` can only choose to use raw data or the data after all above transformations:
1. When using raw count data, the log2fold change is incorrect because it expects log data, and t-test may not be applicable since the data distribution is not normal.
2. When using processed data, because I applied `scale()`, the data is centered around 0 and differential test will be meaningless; even if I use `scale(zero_center=False)`, the data is also changed and the log2 foldchange will be inaccurate.
3. When putting `data.tl.raw_checkpoint()` after `data.tl.log1p()` and before `data.tl.scale()`, the `mean_count_in_cluster` calculated by `find_marker_genes` will be incorrect because the raw data is not truely raw count data.

## Solution
In both Seurat and Scanpy, there is a "layers" in their data structure, so that the `FindMarkers` in Seurat and `rank_genes_groups` in Scanpy can take data in specific layer to run the analysis. 
If stereopy would have "layers" implemented, then I can write like this:
```
data = st.io.read_gef(gef_file, bin_size=bin_size)
data.tl.cal_qc()
data.tl.filter_cells(min_gene=1)
data.tl.raw_checkpoint()
data.tl.normalize_total()
data.tl.log1p()
data.tl.layer_checkpoint('after_log1p') # save the data to 'after_log1p' layer
data.tl.highly_variable_genes()
data.tl.scale()
data.tl.pca()
data.tl.neighbors()
data.tl.leiden()
data.tl.find_marker_genes(layer='after_log1p') # use data in 'after_log1p' layer to run the analysis
```
Where I saved the data after `data.tl.log1p()` so that it can be used to run `find_marker_genes`.

**Comment by tanliwei-coder** [comment]
This is already in our consideration.

**Comment by UglyRay7** [comment]
We do really need this function !!!

**Comment by tanliwei-coder** [comment]
We will distribute it in next version.
