### ISSUE TITLE
Run Error of "Quick Start": AttributeError: 'dict' object has no attribute 'columns'

### ISSUE THREAD

**Issue by Thelistener666** [STOmics/Stereopy#317]
Hi, I'm learning Stereopy. There is an error which I can't fix it. I would be very happy if anyone could help me to solve the problem. I have uploaded the picture
![截屏2024-08-08 21 02 46](https://github.com/user-attachments/assets/8a605b66-8888-4392-a045-f34976d40113)

**Comment by Thelistener666** [comment]
This code can create a file whose name is test.h5ms, though it errors,  the file created! Interesting……

**Comment by tanliwei-coder** [comment]
> This code can create a file whose name is test.h5ms, though it errors, the file created! Interesting……

What happened?

**Comment by Thelistener666** [comment]
I don't know

**Comment by tanliwei-coder** [comment]
Dose the error still occur? And, Whether the h5ms can be created succefully?
