### ISSUE TITLE
 using sc.pl.spatial in Scanpy: 'images' not found in stereo spatial data

### ISSUE THREAD

**Issue by pmf816** [STOmics/Stereopy#318]
Hi there,

Thanks for the tool.

I saved the stereo-seq data as a .h5ad file according to the web manual (adata = st.io.stereo_to_anndata(data, flavor='scanpy', output='stereo_out_T312.h5ad)), and then used Scanpy for downstream analysis. Which went smoothly at first, but when running sc.pl.spatial() the following error occurred.

![截屏2024-08-09 上午10 34 09](https://github.com/user-attachments/assets/26841d83-c654-41a4-ae98-d1c0d0ab1402)

I understand that this error occurs because the 'images' key is not found in the spatial data. However, I'm unsure why this key is missing or how to resolve this issue?  
I look forward to your reply.

The information of the input file is as follows:

![截屏2024-08-09 上午10 34 24](https://github.com/user-attachments/assets/e782ae02-2f22-4ba8-93b5-4f2add47dada)

**Comment by tanliwei-coder** [comment]
Our souce file GEF/GEM dosen't contain image information, so the h5ad file converted from GEF/GEM will also have no image, `sc.pl.spatial` has a parameter `img`, you can pass the corresponding image data through this parameter.

**Comment by pmf816** [comment]
Thanks again, sc.pl.spatial(adata, color=['Wfs1'],sort_order=True, spot_size=2) is work for me.

**Comment by lzyabcccc** [comment]
hi,I encounter the same plotting problem here,I convert stereo spatial data to adata in scanpy. With your code,I plot nothing,and I don't konw the reason.Hope for your reply~
![屏幕截图 2024-10-30 132839](https://github.com/user-attachments/assets/4ef896c1-2694-4e98-990f-4710dc07700b)

**Comment by Bon-jour** [comment]
Hello, I have the same problem when using sc.pl.spatial. How do you transfer pictures into anndata format files?

**Comment by orange511** [comment]
> Hello, I have the same problem when using sc.pl.spatial. How do you transfer pictures into anndata format files?

same problem
