### ISSUE TITLE
data.plt.elbow(pca_res_key='pca')

### ISSUE THREAD

**Issue by Tycooner** [STOmics/Stereopy#322]
it occurs a error "TypeError: 'NoneType' object is not callable"

![image](https://github.com/user-attachments/assets/4e66f882-e492-4052-b68c-8cb130083dd8)

**Comment by tanliwei-coder** [comment]
Which version of stereopy? `data.plt.elbow` is provided since1.0.0.

**Comment by Tycooner** [comment]
1.3.0



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 17:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [STOmics/Stereopy] data.plt.elbow(pca_res_key='pca') (Issue #322)




 
Which version of stereopy? data.plt.elbow is provided since1.0.0.

**Comment by Tycooner** [comment]
1.3.1



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 17:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [STOmics/Stereopy] data.plt.elbow(pca_res_key='pca') (Issue #322)




 
Which version of stereopy? data.plt.elbow is provided since1.0.0.

**Comment by tanliwei-coder** [comment]
I have never encountered this error before, could you show all your codes here?
