### ISSUE TITLE
Discrepancy between cell_bin tutorial and square_bin tutorial

### ISSUE THREAD

**Issue by maximelepetit** [STOmics/Stereopy#324]
Hello,

I noticed a discrepancy in the scale data part between cell_bin tutorial and square_bin tutorial.

It says that : _Scale each gene to unit variance. Clip values exceeding standard deviation 10. If data.tl.scale(zero_center=False) is used, sparse matrix will be used for calculation, which can greatly reduce the memory required for running._

In the cellbin tutorial the command ran is : 
`data.tl.scale()`

In the squarebin tutorial the command ran is : 

`data.tl.scale(max_value=10, zero_center=True)`

Which command is the truth?

Bests

Maxime

**Comment by tanliwei-coder** [comment]
Both are truth, the `zero_center` is **True** by default, in squarebin tutorial, just only set it explicitly, setting `zero_center` to **True** means moving the origin to the center of data, which will lead to almost all zero values in expression matrix become negative values, in this case, expression matrix cannot be saved in sparse matrix, it will cause an increase of memory consumption.
