### ISSUE TITLE
AttributeError: module 'stereo' has no attribute 'io'

### ISSUE THREAD

**Issue by OUMIAOXAIN** [STOmics/Stereopy#326]
Hello! I have an error in Jupyter.

data_info = st.io.read_gef_info(data_path)  
data_info

AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 data_info = st.io.read_gef_info(data_path)  
      2 data_info

AttributeError: module 'stereo' has no attribute 'io'

And I check it.
print(dir(stereo))
['Layout', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'layout']

Why?

**Comment by Rockyman-star** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by tanliwei-coder** [comment]
How did you import the stereo?

**Comment by OUMIAOXAIN** [comment]
I updated the version and resolved the problem.Thank you.



---- Replied Message ----
| From | ***@***.***> |
| Date | 09/09/2024 11:36 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [STOmics/Stereopy] AttributeError: module 'stereo' has no attribute 'io' (Issue #326) |

How did you import the stereo?
