### ISSUE TITLE
AttributeError: 'MSData' object has no attribute 'merged'

### ISSUE THREAD

**Issue by dflower295** [STOmics/Stereopy#327]
Hello, Developer,

I encountered an issue while trying to save my integrated data as an h5ad file. Interestingly, I can save it as an h5ms file without any problems. Could you please explain why this is happening and how I can resolve this error?Below is my code and Error masseage:

import sys
import os

import matplotlib.pyplot as plt
import stereo as st
from stereo.core.ms_data import MSData
from stereo.core.ms_pipeline import slice_generator

import warnings
warnings.filterwarnings('ignore')

data1 = st.io.read_gef('D:/D_flower/stereoopy/pythonProject2/st/Tissue/A3.tissue.gef',bin_type='bins',bin_size=50)

data2 = st.io.read_gef('D:/D_flower/stereoopy/pythonProject2/st/Tissue/A5.tissue.gef',bin_type='bins',bin_size=50)

data3 = st.io.read_gef('D:/D_flower/stereoopy/pythonProject2/st/Tissue/A6.tissue.gef',bin_type='bins',bin_size=50)

ms_data = MSData(_data_list=[data1,data2,data3],_names=["PART","AD","Normal"],_relationship='others',_var_type='intersect')

ms_data.integrate(scope=None,remove_existed=False)
print(ms_data)
ms_data.tl.set_scope_and_mode(scope=slice_generator[:],mode='integrate')
ms_data.tl.cal_qc(scope=slice_generator[:],mode='integrate')
ms_data
#ms_data.plt.violin()
ms_data.plt.spatial_scatter(
            scope=slice_generator[:],
            mode='integrate',
            plotting_scale_width=10, #the width of scale
            reorganize_coordinate=4, #the number of plots in each row
            horizontal_offset_additional=20, #adjustment for horizontal distance
            vertical_offset_additional=20 #adjustment for vertical distance
)

#Filtering
ms_data.tl.filter_cells(min_gene=20,
                       # max_gene=4000,
                        min_n_genes_by_counts=3,
                       # max_n_genes_by_counts=1500,
                        pct_counts_mt=5,
                        scope=slice_generator[:],
                        mode='integrate',
                        inplace=True)
ms_data.tl.filter_genes(min_cells=3,inplace=True)
ms_data.tl.raw_checkpoint()
ms_data.tl.raw

#Normalization
ms_data.tl.normalize_total(scope=slice_generator[:],mode='integrate')
ms_data.tl.log1p(scope=slice_generator[:],mode='integrate')

ms_data.tl.highly_variable_genes(
        min_mean=0.0125,
        max_mean=3,
        max_disp=0.5,
        n_top_genes=2000,
        res_key='highly_variable_genes',
        scope=slice_generator[:],
        mode='integrate'
)
ms_data.plt.highly_variable_genes(res_key='highly_variable_genes')
ms_data.tl.scale(max_value=10,zero_center=True)
ms_data.tl.pca(scope=slice_generator[:],
               mode='integrate',
               use_highly_genes=True,
               n_pcs=30,
               res_key='pca')
ms_data

#Neighborhood graph
ms_data.tl.neighbors(scope=slice_generator[:],
                     mode='integrate',
                     pca_res_key='pca',
                     res_key='neighbors_integrated',
                     n_pcs=50)

#compute spatial neighbors
ms_data.tl.spatial_neighbors(
        neighbors_res_key='neighbors_integrated',
        res_key='spatial_neighbors',
        scope=slice_generator[:],
        mode='integrate'
)

#UMAP
ms_data.tl.umap(scope=slice_generator[:],
                mode='integrate',
                neighbors_res_key='neighbors_integrated',
                res_key='umap_integrated',
                pca_res_key='pca')

ms_data.plt.umap(gene_names=["SNAP25","GFAP","AQP4"],res_key='umap_integrated')

#adata = st.io.stereo_to_anndata(ms_data,flavor='scanpy',output='brain_integrate_seurat.h5ad',split_batches=True)

st.io.write_h5ad(ms_data,use_raw=True,use_result=True,key_record=None,output='./anno_brain.h5ad',split_batches=True)

#st.io.write_h5ms(ms_data,output='./test.h5ms')

plt.show()

Thank you.

**Comment by tanliwei-coder** [comment]
MSData is a multi-sample data structure, it cannot be saved as **h5ad**(h5ad only can be used to save single sample), we only can use st.io.write_h5ms to save MSData to file.

**Comment by dflower295** [comment]
Thanks for your reply
