### ISSUE TITLE
Is there a way to add cellbin's cell type annotation results into GEF, and plot the spatial annotation with cell shape in stereopy?

### ISSUE THREAD

**Issue by ruiliphy** [STOmics/Stereopy#331]

**Comment by tanliwei-coder** [comment]
After reading GEF file as a data object, you can add **annotation** as a column into `data.cells`, like `data.cells['annotation'] = annotation` in which the `annotation` is an array containing cell type annotations, the order of annotations must match the order of cells in `data.cells`, `data.cells` is a DataFrame whose each index consists of **x-coordinate** and **y-coordinate** of the corresponding cell, indexes are string converted from **uint64** whose **higher 32bit** is **x** and **lower 32bit** is **y**, you can then plot by running `data.plt.cluster_scatter(res_key='annotation')`.
