### ISSUE TITLE
Mapping the spatial transcriptome data to the adjacent HE/IHC staining image 

### ISSUE THREAD

**Issue by Yungong1** [STOmics/Stereopy#332]
Hi,

I have Stereo-seq data for six samples paired with adjacent HE staining images. The distance between the HE images and the spatial transcriptome data is ~10 um. Are the any techniques that can accurately align the spatial transcriptome data to the HE images in a manner comparable to 10X Visium?

Thanks a lot for your help!

**Comment by tanliwei-coder** [comment]
Where did you get the Stereo-seq data or what workflow was the Stereo-seq data exported from? The data exported from SAW should have been aligned to image, I can't catch your meaning, wheter you want to align the data to each other?

**Comment by Yungong1** [comment]
> Where did you get the Stereo-seq data or what workflow was the Stereo-seq data exported from? The data exported from SAW should have been aligned to image, I can't catch your meaning, whether you want to align the data to each other?

Thanks so much for your response. Currently, we are applying Stereo-seq to human liver tissue to identify differentially expressed genes (DEGs) between cancerous and normal tissues. To achieve this, we need to align the gene expression data to the adjacent H&E-stained image to classify the bins covering normal or cancerous tissues. While the default pipeline for SAW aligns the gene expression data to the nuclei-stained image of the tissue for cell segmentation, I am wondering if there is any method to align the gene expression data to the adjacent H&E-stained image of the tissue? Thanks!

**Comment by tanliwei-coder** [comment]
Sorry for that I cann't help you, because I am lack of some knowledge, I dont know how to achive your purpose.
