### ISSUE TITLE
TypeError: 'AnnBasedStereoExpData' object is not subscriptable

### ISSUE THREAD

**Issue by xwangda** [STOmics/Stereopy#336]
I would like to reanalyze a data set generated from a published work, and they offer AnnBasedStereoExpData data in GEO. Since I want to perform image-related analysis to understand the spatial information, I would like to subset individual samples to match with antibody staining images. Unfortunately, I got this error :
TypeError: 'AnnBasedStereoExpData' object is not subscriptable.
Could you help to provide a method to subset a specific sample from a merged AnnBasedStereoExpData object? Thanks!

Best

**Comment by tanliwei-coder** [comment]
What is the criteria do you use to subset the merged data?
