### ISSUE TITLE
Extract patches and then merge

### ISSUE THREAD

**Issue by aadimator** [STOmics/Stereopy#338]
Hi Team,

I want to extract patches of a certain size from the StereoExp object, and after processing them, I want to merge them back together. Is there a way to do something like that?

Here's what I'm using to extract the patches:

```python
subs = list()
max_width = data.attr['maxX']
max_height = data.attr['maxY']
chunk_width = 6000
chunk_height = 6000

for x in range(0, max_width, chunk_width):
    for y in range(0, max_height, chunk_height):
        subs.append(data.tl.filter_coordinates(x, x + chunk_width, y, y + chunk_height, inplace=False))
```

But I'm unable to figure out how to merge them back together. I'd really appreciate some pointers in the right direction. I want to use an algorithm but it takes too much time if I run it over the whole sample. That's why I want to extract smaller patches of the data, run that algorithm, and then merge the patches back together.

**Comment by tanliwei-coder** [comment]
What algorithm do you run on the patches?In stereopy, you can use method `merge`([api](https://stereopy.readthedocs.io/en/latest/content/stereo.utils.data_helper.merge.html)) to merge serveral smaples to one, but it will not merge the analysis result.
