### ISSUE TITLE
'stereo' has no attribute 'io' And h5ad2rds.R

### ISSUE THREAD

**Issue by WeijiaSu** [STOmics/Stereopy#340]
Hello,

I was using stereopy to convert gef files to RDS(seurat) and H5ad(scanpy). Following this instruction https://stereopy.readthedocs.io/en/latest/Tutorials/Format_Conversion.html.

When using stereopy version 1.4.0, I got an error that says "AttributeError: module 'stereo' has no attribute 'io'"; The error disappeared when downgrading to version 1.3.0. Using 1,3,0, I was able to convert the gef file to the h5ad file. However, when I tried to convert the h5ad using the script h5ad2rds.R, I got the error shows 
"[1] "Finished! Converting h5ad to h5seurat file at:"
[2] "./SS200000135TL_D1.tissue.gef_bin20.h5seurat"
[1] "h5seurat time consuming: 2.95"
Validating h5Seurat file
Initializing Spatial with data
Adding counts for Spatial
Adding feature-level metadata for Spatial
**Error: Missing required datasets 'levels' and 'values'**
**Execution halted"**

I am not sure if the errors were related to the new gef file that was generated by **SAW_v8.0.2**, I never had this issue with the gef files from SAW_v7*.

Thanks for your help.
Best,
Weijia

**Comment by tanliwei-coder** [comment]
This is so weird, I use stereopy every day but never encounter this error, make sure that in the directory where your notebook is located there is no a py file named stereo.py.
