### ISSUE TITLE
KeyError: 'scope_[0,1]'

### ISSUE THREAD

**Issue by Thelistener666** [STOmics/Stereopy#341]
# Obstain annotation information in obs from each slice, 
# and pass them to MSData with on scope[0,1] with new names id.
# Note that NaN will be used to fill the rest of id column by default.
ms_data.to_integrate(
    scope=slice_generator[0:2],
    res_key='id',
    _from=slice_generator[0:2],
    type='obs',
    item=['annotation','annotation']
)

KeyError                                  Traceback (most recent call last)
Cell In[34], line 4
      1 # Obstain annotation information in obs from each slice, 
      2 # and pass them to MSData with on scope[0,1] with new names id.
      3 # Note that NaN will be used to fill the rest of id column by default.
----> 4 ms_data.to_integrate(
      5     scope=slice_generator[0:2],
      6     res_key='id',
      7     _from=slice_generator[0:2],
      8     type='obs',
      9     item=['annotation','annotation']
     10 )

File ~/anaconda3/envs/stereopy/lib/python3.8/site-packages/stereo/core/ms_data.py:870, in MSData.to_integrate(self, scope, res_key, _from, type, item, fill, cluster)
    868     _index = new_index[isin]
    869     self._scopes_data[scope_key].cells.loc[_index, res_key] = _res
--> 870 if self._scopes_data[scope_key] is self._merged_data:
    871     continue
    872 if self._merged_data is not None:

KeyError: 'scope_[0,1]'

What happened？？？？
Thanks for reply

**Comment by tanliwei-coder** [comment]
Which version of stereopy are you using?
