### ISSUE TITLE
Can not download  drosophila data for demo.

### ISSUE THREAD

**Issue by wangmeijiao** [STOmics/Stereopy#342]
Hi all,

   I  found that the demo dataset mentioned in "https://stereopy.readthedocs.io/en/latest/Tutorials%28Multi-sample%29/MSData_Clustering.html" was broken. Could anyone tell me how to get this dataset?

Best,
Meijiao

**Comment by wangmeijiao** [comment]
The dataset url points to http://116.6.21.110:8090/share/c5d9e7f3-7d66-4154-87e1-a740f4bb4dbc, a raysync link. I guess this is not anonymous and need a user:password?

**Comment by tanliwei-coder** [comment]
No, it dosen't need user:password, I try to download any demo data from the link just now, it can succeed, what is the appearance on your downloading?

**Comment by wangmeijiao** [comment]
It works now, thanks.
