### ISSUE TITLE
Missing gene_names after cell segmentation

### ISSUE THREAD

**Issue by Mollyx06** [STOmics/Stereopy#343]
Thanks for the detailed tutorial!
I'm utilizing stereopy==1.3.0 for cell segmentation, and I noticed that the final gef file reads are blanking out the gene names, with v3  selected for the deep learning model. I'm wondering if this is an issue with the version? Or is there something wrong with my code somewhere?

from stereo import image as im

model = '/data/work/Tutorial/stereopy/seg_models/Deep_Learning_Model_v03/cell_segmetation_v3.0.onnx'
image = '/data/work/Data/SAW-ST-V7/03.register/ssDNA_C03538E6_regist.tif'
output = '/data/work/Results/01_mask_output/ssDNA_C03538E6_regist_v3_mask'
tissue_seg_model = '/data/work/Tutorial/stereopy/seg_models/tissueseg_bcdu_SDI_230523_tf.onnx'

im.cell_seg(
    model_path=model,
    img_path=image,
    out_path=output,
    method='v3',
    tissue_seg_model_path=tissue_seg_model,
    tissue_seg_staining_type='ssDNA',
    gpu='-1' 
)
from stereo.tools.cell_cut import CellCut

cgef_out_dir = "/data/work/Results/02_cell_cut_out"
bgef_path = "/data/work/Data/SAW-ST-V7/02.count/C03538E6.raw.gef"
mask_path = "/data/work/Results/01_mask_output/ssDNA_C03538E6_regist_v3_mask/ssDNA_C03538E6_regist_mask.tif"

cc = CellCut(cgef_out_dir=cgef_out_dir)
out_path = cc.cell_cut(bgef_path=bgef_path, mask_path=mask_path)

data_path = '/data/work/Results/02_cell_cut_out/C03538E6.raw.cellbin_v3.gef'
datav3 = st.io.read_gef(
        file_path=data_path,
        is_sparse=True,
        bin_type='cell_bins',
        )
![image](https://github.com/user-attachments/assets/37bb0486-0e88-4a19-9a82-7dae6ba2c37c)

This is the genes that should appear under SAW
![image](https://github.com/user-attachments/assets/757e7532-096d-42e8-a9c9-a100966aa5da)

**Comment by Mollyx06** [comment]
I updated the version to 1.3.1 according to the announcement, but still missing >1000 genes

**Comment by tanliwei-coder** [comment]
this was a bug of gefpy, upgrade it to latest: `pip install --upgrade gefpy`
