### ISSUE TITLE
Different Clustering Results When Switching Sample Positions in Multi-Sample Analysis

### ISSUE THREAD

**Issue by jh6123** [STOmics/Stereopy#344]
Thanks for the detailed tutorial!
I am following the tutorial quick start for multi-sample analysis. I only swapped the positions of sample 1 and 2 (right and left) while keeping the rest of the preprocessing steps identical. However, the clustering results turned out completely different.

What could be causing this issue?

print(st.__version__)
1.4.0
![Just_position_swap_sample_clustering](https://github.com/user-attachments/assets/31b13977-bf10-412e-9666-f434ab8288f1)

ms_data.plt.cluster_scatter(
            res_key='leiden',
            scope=slice_generator[:],
            mode='integrate',
            plotting_scale_width=1000,          # the width of scale
            reorganize_coordinate=2,          # the number of plots in each row
            horizontal_offset_additional=500,  # adjustment for horizontal distance
            vertical_offset_additional=20     # adjustment for vertical distance
            )

ms_data.plt.cluster_scatter(
            res_key='louvain',
            scope=slice_generator[:],
            mode='integrate',
            plotting_scale_width=1000,          # the width of scale
            reorganize_coordinate=2,          # the number of plots in each row
            horizontal_offset_additional=500,  # adjustment for horizontal distance

            vertical_offset_additional=20     # adjustment for vertical distance
            )

ms_data.plt.cluster_scatter(
            res_key='phenograph',
            scope=slice_generator[:],
            mode='integrate',
            plotting_scale_width=1000,          # the width of scale
            reorganize_coordinate=2,          # the number of plots in each row
            horizontal_offset_additional=500,  # adjustment for horizontal distance
            vertical_offset_additional=20     # adjustment for vertical distance
            )

Thanks for reply

**Comment by tanliwei-coder** [comment]
In **integrate**(default) mode, stereopy will merge the two samples as one to running analysis, swapping the samples will lead to the change of the cells order in expression matrix (the rows order of expression matrix), it will cause the change of the clustering result(the result of those three clustering methods is relative to the order of cells).
