### ISSUE TITLE
植物样本细胞分割

### ISSUE THREAD

**Issue by lvmt** [STOmics/Stereopy#346]
你好，我最近做了一个植物样本：番茄，做了**ssDNA染色**和**细胞壁染色**；

我用image studio分别测试了ssDNA染色和细胞壁染色的细胞分割结果；
    ssDNA基于核分割，可以分割出细胞核，但是在进行细胞质延申的时候，效果不是很好； 
    在用细胞壁进行细胞分割时，imagestudio将细胞壁当成了细胞核进行分割。分割结果完全不正确。 

了解到imagestudio是借助stereopy进行的分割，想问一下你们后面会开发**基于细胞壁的细胞分割方法**吗？
然后针对植物样本，你们有什么好的方法吗？ 

谢谢

**Comment by tanliwei-coder** [comment]
可以尝试下[Cellpose](https://stereopy.readthedocs.io/en/latest/Tutorials/Cell_Segmentation.html#Cellpose)方法
