### ISSUE TITLE
Add annotations for the selecting areas

### ISSUE THREAD

**Issue by hejian41** [STOmics/Stereopy#354]
Hi, liwei

I aim to distinguish tissue parts to analyze cell cluster distributions spatially. Is there a method to annotate ROIs selected using _interact_spatial_scatter_?

Thanks

**Comment by tanliwei-coder** [comment]
You can get a **sub-object** for each selected area following this [section](https://stereopy.readthedocs.io/en/latest/Tutorials/High_Resolution_Export.html#Getting-a-sub-object) and add annotations through the **sub-objects**,

example code:

```

# get a sub-object of a selected area
selected_exp_data = ins.selected_exp_data 
data.cells.loc[selected_exp_data.cell_names, 'annotation'] = 'cell_type'

```

**Comment by hejian41** [comment]
Great! thx ~
