### ISSUE TITLE
gene name substitution

### ISSUE THREAD

**Issue by ASasasdasfasfasfasfasf** [STOmics/Stereopy#355]
hello 
I'm using Stereopy tutorial, I found two columns in my genes, there is an extra column “real_gene_name” and 'gene_name' is ENSMUSG00000000001.4 This kind of number, I tried to replace it but it seems that he can't replace it, is there any good way to do it, looking forward to your reply!
![Uploading 1732590042251.jpg…]()

**Comment by tanliwei-coder** [comment]
As you can see, the `real_gene_name` is the real names of the genes, on the other hand, the `gene_name` is the IDs of the genes, which is added when the file is a new version GEF, `gene_name` is actually the index of `data.genes.var`, if you want to use `real_gene_name` as index, you can set the parameter `gene_name_index` to True when using `st.io.read_gef` to read GEF file.
