### ISSUE TITLE
Problem with function "tl.spatial_neighbors" in stereopy.

### ISSUE THREAD

**Issue by Lp3533** [STOmics/Stereopy#356]
Hello, I have trouble when I analyze my spatial transcriptome data. I follow the official course and was blocked when ran "tl.spatial_neighbors". The following are my codes and Error:

`ms_data.tl.spatial_neighbors(
        neighbors_res_key='neighbors',
        res_key='spatial_neighbors',
        scope=slice_generator[:],
        mode='integrate'
        )`

`[2024-11-27 08:21:47][Stereo][5565][MainThread][139879157327680][ms_pipeline][123][INFO]: data_obj(idx=0) in ms_data start to run spatial_neighbors
[2024-11-27 08:21:47][Stereo][5565][MainThread][139879157327680][st_pipeline][41][INFO]: start to run spatial_neighbors...
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [23], in <cell line: 1>()
----> 1 ms_data.tl.spatial_neighbors(
      2         neighbors_res_key='neighbors',
      3         res_key='spatial_neighbors',
      4         scope=slice_generator[:],
      5         mode='integrate'
      6         )

File ~/.local/lib/python3.8/site-packages/stereo/core/ms_pipeline.py:215, in MSDataPipeLine.__getattr__.<locals>.temp(*args, **kwargs)
    212     kwargs["mode"] = self.__mode
    214 if kwargs["mode"] == "integrate":
--> 215     return self._use_integrate_method(item, *args, **kwargs)
    216 elif kwargs["mode"] == "isolated":
    217     self._run_isolated_method(item, *args, **kwargs)

File ~/.local/lib/python3.8/site-packages/stereo/core/ms_pipeline.py:124, in MSDataPipeLine._use_integrate_method(self, item, *args, **kwargs)
    121             return new_attr(*args, **kwargs)
    123 logger.info(f'data_obj(idx=0) in ms_data start to run {item}')
--> 124 return new_attr(
    125     # ms_data_view.merged_data.__getattribute__(self.__class__.ATTR_NAME),
    126     getattr(ms_data_view.merged_data, self.__class__.ATTR_NAME),
    127     *args,
    128     **kwargs
    129 )
File ~/.local/lib/python3.8/site-packages/stereo/core/st_pipeline.py:43, in logit.<locals>.wrapped(*args, **kwargs)
     41 logger.info('start to run {}...'.format(func.__name__))
     42 tk = tc.start()
---> 43 res = func(*args, **kwargs)
     44 logger.info('{} end, consume time {:.4f}s.'.format(func.__name__, tc.get_time_consumed(key=tk, restart=False)))
     45 return res

File ~/.local/lib/python3.8/site-packages/stereo/core/st_pipeline.py:1084, in StPipeline.spatial_neighbors(self, neighbors_res_key, n_neighbors, res_key)
   1075 """
   1076 Create a graph from spatial coordinates using Squidpy.
   1077 
   (...)
   1081 :return: Spatial neighbors result is stored in `self.result` where the result key is `'spatial_neighbors'`.
   1082 """
   1083 from ..io.reader import stereo_to_anndata
-> 1084 import squidpy as sq
   1085 neighbor, connectivities, dists = copy.deepcopy(self.get_neighbors_res(neighbors_res_key))
   1086 if isinstance(self.data, AnnBasedStereoExpData):

File ~/.local/lib/python3.8/site-packages/squidpy/__init__.py:1, in <module>
----> 1 from squidpy import gr, im, pl, read, datasets
      3 __author__ = __maintainer__ = "Theislab"
      4 __email__ = ", ".join(
      5     [
      6         "giovanni.palla@helmholtz-muenchen.de",
      7         "hannah.spitzer@helmholtz-muenchen.de",
      8     ]
      9 )
File ~/.local/lib/python3.8/site-packages/squidpy/gr/__init__.py:2, in <module>
      1 """The graph module."""
----> 2 from squidpy.gr._build import spatial_neighbors
      3 from squidpy.gr._nhood import nhood_enrichment, centrality_scores, interaction_matrix
      4 from squidpy.gr._sepal import sepal

File ~/.local/lib/python3.8/site-packages/squidpy/gr/_build.py:9, in <module>
      6 from itertools import chain
      7 import warnings
----> 9 from scanpy import logging as logg
     10 from anndata import AnnData
     11 from anndata.utils import make_index_unique

File ~/.local/lib/python3.8/site-packages/scanpy/__init__.py:16, in <module>
     14 from . import tools as tl
     15 from . import preprocessing as pp
---> 16 from . import plotting as pl
     17 from . import datasets, logging, queries, external, get, metrics, experimental
     19 from anndata import AnnData, concat

File ~/.local/lib/python3.8/site-packages/scanpy/plotting/__init__.py:1, in <module>
----> 1 from ._anndata import (
      2     scatter,
      3     violin,
      4     ranking,
      5     clustermap,
      6     tracksplot,
      7     dendrogram,
      8     correlation_matrix,
      9     heatmap,
     10 )
     11 from ._dotplot import DotPlot, dotplot
     12 from ._matrixplot import MatrixPlot, matrixplot

File ~/.local/lib/python3.8/site-packages/scanpy/plotting/_anndata.py:28, in <module>
     26 from .._utils import sanitize_anndata, _doc_params, _check_use_raw
     27 from .._compat import Literal
---> 28 from . import _utils
     29 from ._utils import scatter_base, scatter_group, setup_axes, check_colornorm
     30 from ._utils import ColorLike, _FontWeight, _FontSize

File ~/.local/lib/python3.8/site-packages/scanpy/plotting/_utils.py:35, in <module>
     29 _FontSize = Literal[
     30     'xx-small', 'x-small', 'small', 'medium', 'large', 'x-large', 'xx-large'
     31 ]
     32 VBound = Union[str, float, Callable[[Sequence[float]], float]]
---> 35 class _AxesSubplot(Axes, axes.SubplotBase, ABC):
     36     """Intersection between Axes and SubplotBase: Has methods of both"""
     39 # -------------------------------------------------------------------------------
     40 # Simple plotting functions
     41 # -------------------------------------------------------------------------------

TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

**Comment by tanliwei-coder** [comment]
Maybe due to unknown reasons, some dependencies were not fully installed, you can reinstall stereopy by the following command and then try the `spatial_neighbors` again.

> pip install stereopy==1.5.0 --force-reinstall --no-cache-dir
