### ISSUE TITLE
Problem about tissue segmentation

### ISSUE THREAD

**Issue by chen496923026** [STOmics/Stereopy#357]
Tried to perform tissue segment as listed here
https://stereopy.readthedocs.io/en/latest/Tutorials/Tissue_Segmentation.html
But when I run from 'stereo.image.tissue_cut import SingleStrandDNATissueCut' , an erro occurs.

The necessary packages mentioned in the tutorial have been installed.

Traceback as follow:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File [~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/image/__init__.py:6](http://localhost:8888/lab/workspaces/auto-N/tree/~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/image/__init__.py#line=5)
      5 from .pyramid import merge_pyramid, create_pyramid
----> 6 from .segmentation.segment import cell_seg
      7 from .segmentation.seg_utils.v3 import CellSegPipeV3 as cell_seg_v3

File [~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/image/segmentation/segment.py:7](http://localhost:8888/lab/workspaces/auto-N/tree/~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/image/segmentation/segment.py#line=6)
      6 from stereo.constant import VersionType
----> 7 from stereo.image.segmentation.seg_utils.v1 import CellSegPipeV1
      8 from stereo.image.segmentation.seg_utils.v1_pro import CellSegPipeV1Pro

ModuleNotFoundError: No module named 'stereo.image.segmentation.seg_utils'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 from stereo.image.tissue_cut import SingleStrandDNATissueCut

File [~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/image/__init__.py:24](http://localhost:8888/lab/workspaces/auto-N/tree/~/miniconda3/envs/st/lib/python3.8/site-packages/stereo/image/__init__.py#line=23)
     11 except ImportError as e:
     12 #     errmsg = """function `merge_pyramid`, `create_pyramid`, `cell_seg`, `cell_seg_v3`, `tissue_cut`, 
     13 # `cell_seg_deepcell` is not import at `stereo.image` module.
   (...)
     21 # ************************************************
     22 #     """
     23     errmsg = "Some necessary modules may not be installed. More information please refer to the documentation."
---> 24     raise ImportError(errmsg)

ImportError: Some necessary modules may not be installed. More information please refer to the documentation.

**Comment by tanliwei-coder** [comment]
It seems that stereopy was not installed fully, you can try to reinstall stereopy:

> pip install stereopy==1.5.0 --force-reinstall --no-cache-dir

Then, install the necessary dependencies.
