### ISSUE TITLE
Stereopy in the output of images, want to not through the interactive click, directly generate static images how to operate？

### ISSUE THREAD

**Issue by Jyyy9689** [STOmics/Stereopy#361]
For example, after running data.plt.spatial_scatter(), not by clicking on the component, directly generated pdf or png how to do?

**Comment by tanliwei-coder** [comment]
each method that supports exporting plot as image by clicking button has two parameters `out_path` and `out_dpi`, which are respectively used to set the save path(including file name) and dpi of the exported image.
